Minor correction to V100 memory on interactive GPU examples
rcgsheffield/sheffield_hpc pull request #1112
Opened 2020-11-03 18:42 UTC by ptheywood

This applies to the V100 node(s) in the gpu and dcs-gpu partitions, but not the 16GB V100s in the dcs-acad partition, which is an special case with limited access.

2020-11-04 15:00 UTC, willfurnass requested changes
Hi @ptheywood. Good spot.  See small suggestion in-line.  

Also, I think we should add a brief note to `bessemer/groupnodes/dcs-acad-gpu-nodes.rst` making folks aware that most other GPU nodes in the cluster have 32GB/device.

2020-11-05 11:22 UTC, willfurnass commented
@ptheywood I've suggested some changes for addressing these comments: https://github.com/ptheywood/sheffield_hpc/pull/1

2020-11-05 11:32 UTC, ptheywood commented
@willfurnass I've merged your suggested changes into the branch/pr.

2020-11-05 11:32 UTC, willfurnass approved these changes

2020-11-05 11:44 UTC, merged

2020-11-05 11:45 UTC, willfurnass commented
Thanks @ptheywood