Adding a compute resource selection optimization guide
rcgsheffield/sheffield_hpc pull request #1151
Opened 2021-02-10 16:01 UTC by jkwmoore

This includes adding a reference info section so imports of specific sections can be done more than once.

Additionally this adds a global.rst file which is added at the front of all pages - this contains a substitution of |br| to make a <br/> in HTML inline where this is needed.

This is not done on each page in order to avoid multiple definition warnings. Further substitutions can be made as / when needed by adding these to the global.rst file.

Appropriate edits to the conf.py have been made to pull this in but also exclude it from being sourced.

2021-04-23 09:00 UTC, desmfryan reviewed
Hi James

this looks really good.

A few comments

1) Determining time requirements
iceberg needs to be changed to ShARC/Bessemer  (I know you didn't add this but a good opportunity to fix)....lin 44

2) Memory allocation limits - for batch jobs 2 Gb(default)/~6144 Gb(max).......this may be a bit confusing for users using smp on ShARC. Might be worth explicitly stating mpi despite it mentioned earlier.

3) Filestore limits: the link in the text does not point to anything. I checked out the PR, built the docs and checked this :|

My personal opinion is that if a docs PR looks ~95-100% correct then it should be merged asap. Then the published docs can be refined post 're-read' and any highlighted ambiguities.

Best wishes,

Des

2021-04-29 12:57 UTC, willfurnass requested changes

2021-04-29 12:57 UTC, willfurnass commented on hpc/Choosing-appropriate-resources.rst
> +It is important to be aware that the resource requests that you make are not flexible, if your job exceeds what you have requested for it the scheduler will terminate your job abruptly and without an
```suggestion
It is important to be aware that the resource requests that you make are not flexible: if your job exceeds what you have requested for it the scheduler will terminate your job abruptly and without any warning. This means that it is safest to over estimate your job's requirements if they cannot be accurately and precisely known in advance.
```

2021-04-29 12:57 UTC, willfurnass commented on hpc/Choosing-appropriate-resources.rst
> +* Allocations larger than the scheduler can satisfy with the available resources **will never start.**
```suggestion
* Allocations larger than the scheduler can ever satisfy with the available resources **will never start.**
```

2021-04-29 12:57 UTC, willfurnass commented on hpc/Choosing-appropriate-resources.rst
> +It is also important to note that the Sheffield HPC clusters have been designed to fulfil different purposes. ShARC is a capability cluster designed to run very large compute jobs that will use multi
Add 'choice of cluster' to list of 4 bullet points at the top of the page? Hmm...

2021-04-29 12:57 UTC, willfurnass commented on hpc/Choosing-appropriate-resources.rst
> +With this in mind, you should prioritize putting smaller core count jobs onto Bessemer and massively parallel jobs onto ShARC while utilizing a form of MPI.
```suggestion
With this in mind, you should prioritize putting smaller core count jobs onto Bessemer and massively parallel jobs onto ShARC (while utilizing a form of :ref:`MPI <parallel_MPI>`).
```

2021-04-29 12:57 UTC, willfurnass commented on hpc/Choosing-appropriate-resources.rst
> +It is also important to note that the Sheffield HPC clusters have been designed to fulfil different purposes. ShARC is a capability cluster designed to run very large compute jobs that will use multi
```suggestion
It is also important to note that the Sheffield HPC clusters have been designed to fulfil different purposes. ShARC is for the most part a *capability* cluster designed to run larger compute jobs that will use multiple nodes. Bessemer is a *capacity* cluster designed to run smaller compute jobs which will fit on a single node.
```

2021-04-29 12:57 UTC, willfurnass commented on referenceinfo/TimeAllocationLimits.rst
> +==============================
Duplicates info from `hpc/scheduler/submit.rst` - better to have one/both places x-ref a central store of this info?

2021-04-29 12:57 UTC, willfurnass commented on hpc/Choosing-appropriate-resources.rst
> +The time allocation limits will differ between job types and by cluster - a summary of these differences can be seen above. Time requirements are highly dependent on how many CPU cores your job is us
"will drastically" -> "may significantly decrease the amount of time the job spends running, depending on how optimally the software you are using supports parallelisation."

2021-04-29 12:57 UTC, willfurnass commented on hpc/Choosing-appropriate-resources.rst
> +Determining time requirements using timing commands in your script:
```suggestion
Determining time requirements using timing commands in your script
```

2021-04-29 12:57 UTC, willfurnass commented on hpc/Choosing-appropriate-resources.rst
> +A way of deducing the wall_clock_time used by a job is to use the date or the timeused command within the script file. The date command is part of the Linux operating system whereas the timeused comm
s/wall_clock_time/'wall clock' time/

2021-04-29 12:57 UTC, willfurnass commented on hpc/Choosing-appropriate-resources.rst
> +A way of deducing the wall_clock_time used by a job is to use the date or the timeused command within the script file. The date command is part of the Linux operating system whereas the timeused comm
Iceberg is dead

2021-04-29 12:57 UTC, willfurnass commented on hpc/Choosing-appropriate-resources.rst
> +A way of deducing the wall_clock_time used by a job is to use the date or the timeused command within the script file. The date command is part of the Linux operating system whereas the timeused comm
Would suggest using scheduler reporting info for benchmark info in first instance if not using interactive session.

2021-04-29 12:57 UTC, willfurnass commented on hpc/Choosing-appropriate-resources.rst
> +Using the **timeused** command: ::
Would omit this until we have this functionality on both clusters.

2021-04-29 12:57 UTC, willfurnass commented on referenceinfo/ListingQueues.rst
> +On Bessemer you can list the queues with: ::
partitions

2021-04-29 12:57 UTC, willfurnass commented on referenceinfo/FileStoreLimits.rst
> +Every HPC user is allocated a file-storage area of their own. Please read the section on  :ref:`filestore` for the clusters for further information. Any attempt to exceed this allocation during the e
"this allocation" -> could note that only applies to areas with quotas.

2021-04-29 12:57 UTC, willfurnass commented on referenceinfo/CpuAllocationLimits.rst
> +==============================
Upper limits for private queues/nodes may differ.

2021-04-29 12:57 UTC, willfurnass commented on referenceinfo/MemoryAllocationLimits.rst
> +==============================
Upper limits for private queues/nodes may differ.

2021-04-29 12:57 UTC, willfurnass commented on hpc/Choosing-appropriate-resources.rst
> +* :ref:`Specific group nodes on ShARC<groupnodes_sharc>`
Could note that these are non-exhaustive lists (few private nodes ahve public docs)

2021-04-29 12:57 UTC, willfurnass commented on hpc/Choosing-appropriate-resources.rst
> +One method to determine how much space your jobs are likely to consume is to run an example job within a specific directory saving the output within.
Assuming no churn in `$PWD` during the job?

2021-04-29 12:57 UTC, willfurnass commented on hpc/Choosing-appropriate-resources.rst
> +For SMP only type parallel processing jobs: you can use a maximum of 16 cores on ShARC and 40 cores on Bessemer. Ideally you should use Bessemer as you can not only access more cores, you are using m
With public nodes

2021-04-29 12:57 UTC, willfurnass commented on hpc/Choosing-appropriate-resources.rst
> +For MPI type parallel processing jobs: these can only run on ShARC and although you can access as many cores as are available you must consider how long a job will take to queue waiting for resources
Could note that multi-node jobs typically require MPI for inter-proc communication but MPI can also be used / may be required for comms between a set of processes all packed onto a single node.

2021-04-29 12:57 UTC, willfurnass commented on hpc/Choosing-appropriate-resources.rst
> +The CPU allocation limits will differ between job types and by cluster - a summary of these differences can be seen above. It is important to note that SLURM and SGE will request CPU on a different b
"It is important to note that SLURM and SGE will request CPU on a different basis as detailed above." -> what's meant by this?

2021-04-29 12:57 UTC, willfurnass commented on referenceinfo/TimeAllocationLimits.rst
> +==============================
Values might differ slightly for private nodes.

2021-04-29 12:57 UTC, willfurnass commented on referenceinfo/ListingQueues.rst
> +As Bessemer has non-homogenous nodes you can list more information by formatting the output, e.g.: ::
Makes it sound as though only Bessemer has non-homogeneous nodes.

2021-04-29 12:57 UTC, willfurnass commented on referenceinfo/FileStoreLimits.rst
> +Each filestore has the relevant detail and performance characteristics listed within the section on :ref:`filestore`, this will indicate where your program is best suited to run from.
Could add that may need to use multiple filestores during a project or even as part of one job.

2021-04-29 12:57 UTC, willfurnass commented on hpc/Choosing-appropriate-resources.rst
> +* cumulative memory_usage*seconds ( mem ).
'cumulative memory_usage*seconds' -> omit?

2021-04-29 12:57 UTC, willfurnass commented on hpc/Choosing-appropriate-resources.rst
> +      myprog < mydata.txt > myresults.txt\
omit `\`

2021-04-29 12:57 UTC, willfurnass commented on hpc/Choosing-appropriate-resources.rst
> +      myprog < mydata.txt > myresults.txt\
omit `\`

2021-04-29 12:57 UTC, willfurnass commented on hpc/Choosing-appropriate-resources.rst
> +      #$ -l h_rt=120:00:00
Suggest making wall time the same for both examples

2021-04-29 12:57 UTC, willfurnass commented on hpc/Choosing-appropriate-resources.rst
> +For both parallel processing methods you should run several test jobs using the tips from the `Time allocation <#time-allocation-limits>`_ section with various numbers of cores to assess what factor
Could add things about 
 - extrapolating from smaller test jobs
 - amdahl's law (if not by name) i.e. imperfect scaling
 - jobs may be CPU, memory bandwidth or IO bound - detailed benchmarking/profiling for exploring limiting factors is beyond the scope of this guide.

2021-04-29 13:12 UTC, jkwmoore commented on hpc/Choosing-appropriate-resources.rst
> +It is also important to note that the Sheffield HPC clusters have been designed to fulfil different purposes. ShARC is a capability cluster designed to run very large compute jobs that will use multi
I think you are probably right, that is going to be a great way to telegraph there is a difference please look into it.

Would you propose adding another bullet then another very small section called '**Cluster Selection**' and 

```
It is also important to note that the Sheffield HPC clusters have been designed to fulfil different purposes. ShARC is a capability cluster designed to run very large compute jobs that will use multiple nodes. Bessemer is a capacity cluster designed to run compute jobs which will sit within a single node.

With this in mind, you should prioritize putting smaller core count jobs onto Bessemer and massively parallel jobs onto ShARC while utilizing a form of MPI. 
```

2021-04-29 13:13 UTC, jkwmoore commented on referenceinfo/TimeAllocationLimits.rst
> +==============================
Yeah I think this is where we want to use a single reference page then use includes?

2021-04-29 14:29 UTC, jkwmoore commented on hpc/Choosing-appropriate-resources.rst
> +* cumulative memory_usage*seconds ( mem ).
This will be amended in my next commit.

2021-04-29 14:29 UTC, jkwmoore commented on hpc/Choosing-appropriate-resources.rst
> +      myprog < mydata.txt > myresults.txt\
This will be amended in my next commit.

2021-04-29 14:29 UTC, jkwmoore commented on hpc/Choosing-appropriate-resources.rst
> +      myprog < mydata.txt > myresults.txt\
This will be amended in my next commit.

2021-04-29 14:29 UTC, jkwmoore commented on hpc/Choosing-appropriate-resources.rst
> +      #$ -l h_rt=120:00:00
This will be amended in my next commit.

2021-04-29 14:41 UTC, jkwmoore commented on hpc/Choosing-appropriate-resources.rst
> +For both parallel processing methods you should run several test jobs using the tips from the `Time allocation <#time-allocation-limits>`_ section with various numbers of cores to assess what factor
Yes I think I will amend this with a bit more detail now.

2021-04-29 16:09 UTC, jkwmoore commented on hpc/Choosing-appropriate-resources.rst
> +For both parallel processing methods you should run several test jobs using the tips from the `Time allocation <#time-allocation-limits>`_ section with various numbers of cores to assess what factor
Added a bit more on this - complete with CSS hacky solutions.

2021-04-29 16:14 UTC, jkwmoore commented on hpc/Choosing-appropriate-resources.rst
> +The time allocation limits will differ between job types and by cluster - a summary of these differences can be seen above. Time requirements are highly dependent on how many CPU cores your job is us
Sorted in 83a6f4aa784ad10c18a8003a153fca6da634694b

2021-04-29 16:19 UTC, jkwmoore commented on hpc/Choosing-appropriate-resources.rst
> +A way of deducing the wall_clock_time used by a job is to use the date or the timeused command within the script file. The date command is part of the Linux operating system whereas the timeused comm
Resolving iceberg bit with 97a0f215ed7ed3f3fb47cacae80ec14568b87943 and wallclocl with 97a0f215ed7ed3f3fb47cacae80ec14568b87943

I didn't want to mention using the scheduler as it is non-specific i.e. will include IO wait / filesystem and everything in the job but we can certainly amend to include it with said caveats.

2021-04-29 16:21 UTC, jkwmoore commented on hpc/Choosing-appropriate-resources.rst
> +A way of deducing the wall_clock_time used by a job is to use the date or the timeused command within the script file. The date command is part of the Linux operating system whereas the timeused comm
Could you add the command to the clusters? https://github.com/rcgsheffield/sheffield_hpc/issues/1193

Not actually sure where the original timeused code resides at present.

2021-04-29 16:22 UTC, jkwmoore commented on hpc/Choosing-appropriate-resources.rst
> +Using the **timeused** command: ::
Yeah I was going to pause the merge until https://github.com/rcgsheffield/sheffield_hpc/issues/1193 is resolved :)

2021-04-29 16:23 UTC, jkwmoore commented on hpc/Choosing-appropriate-resources.rst
> +The CPU allocation limits will differ between job types and by cluster - a summary of these differences can be seen above. It is important to note that SLURM and SGE will request CPU on a different b
`-pe <env> <nn>` versus `-c <nn>` I believe.

We could add a relative link to the table?

2021-04-29 16:26 UTC, jkwmoore commented on hpc/Choosing-appropriate-resources.rst
> +For MPI type parallel processing jobs: these can only run on ShARC and although you can access as many cores as are available you must consider how long a job will take to queue waiting for resources
Hopefully addressed in 9d817a28b5caec9ce8f4c8b1101ff96bef45f556

2021-04-29 16:32 UTC, jkwmoore commented on referenceinfo/CpuAllocationLimits.rst
> +==============================
I think this is currently addressed at the end of the main page where we discuss special limits / alternative queues - though we could add a quick blurb under this table?

2021-04-29 16:34 UTC, jkwmoore commented on referenceinfo/FileStoreLimits.rst
> +Every HPC user is allocated a file-storage area of their own. Please read the section on  :ref:`filestore` for the clusters for further information. Any attempt to exceed this allocation during the e
Hopefully resolved in 1e640f31c68300100a80310daf67086b0403d52b

2021-04-29 16:37 UTC, jkwmoore commented on referenceinfo/FileStoreLimits.rst
> +Each filestore has the relevant detail and performance characteristics listed within the section on :ref:`filestore`, this will indicate where your program is best suited to run from.
And also hopefully sorted in e5611223d6e07a07d2b41fdd5f48e87171ab42ae

2021-04-29 16:39 UTC, jkwmoore commented on referenceinfo/ListingQueues.rst
> +On Bessemer you can list the queues with: ::
I think this is a tricky one since one saying partitions and the other queues might confuse people. Will amend this later with an explanation that they are the same thing.

2021-04-29 16:43 UTC, jkwmoore commented on referenceinfo/ListingQueues.rst
> +As Bessemer has non-homogenous nodes you can list more information by formatting the output, e.g.: ::
We could amend this as - 'As Bessemer is a non-homogenous cluster, you can list the different partitions, their time limits, number of cores per node and how many nodes are available in the partition with: ::'

2021-04-29 16:44 UTC, jkwmoore commented on referenceinfo/MemoryAllocationLimits.rst
> +==============================
Same thing as with the CpuAllocationLimits.rst - it might be worth adding a quick blurb about this here rather than relying on the main page last section?

2021-05-06 13:05 UTC, merged

2021-05-11 11:59 UTC, jkwmoore commented on referenceinfo/ListingQueues.rst
> +As Bessemer has non-homogenous nodes you can list more information by formatting the output, e.g.: ::
This was amended as 'As Bessemer has non-homogenous nodes you can list more information by'