Update to include scheduler/MPI aware containers
rcgsheffield/sheffield_hpc pull request #1202
Opened 2021-04-29 10:15 UTC by jkwmoore

Updates to clarify the available methods for dealing with this, minor corrections and again trailing white spaces are gone.

2021-04-29 12:53 UTC, desmfryan reviewed
James

Looks good.

The only minor niggle is:
e.g. the cluster's ``/fastdata`` directory will be automatically visible within a container started on the cluster

I think I might say something like:
e.g. the cluster's directories will be automatically visible within a container started on the cluster

so that it is not interpreted as /fastdata only....despite your earlier wording.

Cheers,

Des

2021-04-29 14:58 UTC, willfurnass requested changes

2021-04-29 14:58 UTC, willfurnass commented on sharc/software/apps/singularity.rst
> +Considerations for MPI or Scheduler aware containers
Do we want something v. short and simple like the following?

```
MPI and Singularity
-------------------

If you try running MPI within a Singularity container on a single node
the MPI implementation may auto-detect that its processes are running under the SGE job scheduler 
and will try to read a SGE file containing information on the CPU cores SGE has allocateed to that job.
This will fail unless you run your container with a ``--bind $PE_HOSTFILE:$PE_HOSTFILE:ro`` argument e.g.: ::

    singularity exec --bind $PE_HOSTFILE:$PE_HOSTFILE:ro /usr/local/packages/singularity/images/example.simg /home/$USER/my_script.sh

For a more complete guide to using MPI with Singularity (inc. multi-node jobs) `see the Singularity project's documentation <https://sylabs.io/guides/3.7/user-guide/mpi.html>`__.
```

2021-04-30 09:06 UTC, jkwmoore commented on sharc/software/apps/singularity.rst
> +Considerations for MPI or Scheduler aware containers
Yes, I think being prescriptive with ` --bind $PE_HOSTFILE:$PE_HOSTFILE:ro` is probably for the best - will amend this section shortly.

2021-04-30 09:23 UTC, jkwmoore commented on sharc/software/apps/singularity.rst
> +Considerations for MPI or Scheduler aware containers
Just addressed this in 1911fdcb83ce251e6dbffd63dec0bea049fb8647

2021-04-30 09:27 UTC, willfurnass approved these changes

2021-04-30 09:29 UTC, merged