New account file transfer with rsync FAQ
rcgsheffield/sheffield_hpc pull request #1617
Opened 2023-01-11 12:42 UTC by nikishe

New Account file transfer with rsync FAQ

2023-01-11 12:58 UTC, Carldkennedy requested changes
Add a few comments

2023-01-11 12:58 UTC, Carldkennedy commented on FAQs.rst
> +* Log into your new username in the cluster you want to copy to and create a folder named "OldUserAccount".
I think you need to add a new line before the bullet point

2023-01-11 12:58 UTC, Carldkennedy commented on FAQs.rst
> +* Log into your old account and run the RSYNC command. There are two ways to run it, the first examples assumes you are copying the files to the new account on the same cluster node(e.g old account o
* Log into your old account and run the RSYNC command. Here we show two examples. 
1) You want to copy your files to the new account on the same cluster node (e.g old account on Bessemer to new account on Bessemer), here we are only going to use the "avP" options as we dont need to compress the data.

2023-01-11 12:58 UTC, Carldkennedy commented on FAQs.rst
> +The other example assumes you are copying the files to the new account on a different cluster node(e.g old account on Bessemer to new account on Sharc/Stannage), here we are going to use the option "
2) You want to copy your files to the new account on a different cluster node (e.g old account on Bessemer to new account on Sharc/Stannage), here we are going to use the option "avzP" as we are going to transfer data over the internet, and it will be faster if it is compressed.

2023-01-11 12:58 UTC, Carldkennedy commented on FAQs.rst
> +To transfer data between your old account and your new account you could make use of either `SCP <https://docs.hpc.shef.ac.uk/en/latest/hpc/transferring-files.html#using-scp-in-the-terminal>`__ or `R
I'd also add what each of the options does and maybe about seeing full details using `man rsync`

2023-01-11 13:02 UTC, Carldkennedy commented on FAQs.rst
> +To transfer data between your old account and your new account you could make use of either `SCP <https://docs.hpc.shef.ac.uk/en/latest/hpc/transferring-files.html#using-scp-in-the-terminal>`__ or `R
Also might want to add a warning about rsync push deleting files on remote if they don't exist on local?

2023-01-11 15:10 UTC, Carldkennedy commented on FAQs.rst
> +I Have a new account, how do I transfer data from my old account
```suggestion
I have a new account, how do I transfer data from my old account
```

2023-01-11 15:12 UTC, Carldkennedy approved these changes

2023-01-11 15:13 UTC, jkwmoore requested changes
Should be some changes attached but otherwise LGTM.

2023-01-11 15:34 UTC, jkwmoore commented on FAQs.rst
> +The other example assumes you are copying the files to the new account on a different cluster node(e.g old account on Bessemer to new account on Sharc/Stannage), here we are going to use the option "
*when networking will affect this choice.

2023-01-11 15:47 UTC, merged

2023-01-12 09:08 UTC, willfurnass commented on FAQs.rst
> +To transfer data between your old account and your new account you could make use of either `SCP <https://docs.hpc.shef.ac.uk/en/latest/hpc/transferring-files.html#using-scp-in-the-terminal>`__ or `r
scp (and sftp) can also preserve modification times; not a distinguishing feature from rsync.  However, worth mentoining that preserving modification times is typically what's required (and needs explicitly enabling).

I like the idea of recommending just one way of doing this though (using rsync) so as to keep this section concise.

2023-01-12 09:11 UTC, willfurnass commented on FAQs.rst
> +1. You want to copy the files to the new account on the same cluster node(e.g old account on Bessemer to new account on Bessemer), here we are only going to use the "avP" options as we dont need to c
Suggest omitting mention of compression to make more concise.

Is 'avP' definitely what's required here?  Think 'a' enables archive mode, which preserves a whole bunch of things in addition to timestamps (inc ownership, which we _don't_ want here).  Also, users will want 'r' if wanting to recursively copy a directory plus contents.  Suggest running some tests and checking man page for rsync.

2023-01-12 09:13 UTC, willfurnass commented on FAQs.rst
> +* Log into your new username in the cluster you want to copy to and create a folder named "OldUserAccount".
Could say that doing this so don't accidentally overwrite files in new account home dir?

2023-01-12 09:14 UTC, willfurnass commented
Sorry, again late to the party.  Added some suggestions that could be addressed via a 2nd PR.

2023-01-12 09:55 UTC, jkwmoore commented on FAQs.rst
> +1. You want to copy the files to the new account on the same cluster node(e.g old account on Bessemer to new account on Bessemer), here we are only going to use the "avP" options as we dont need to c
afaik `-a `/`archive` can't and won't preserve owners unless you are the owner already, though I cannot say I have checked in recent memory. iirc `-a `should imply recursive and I do expect that it is what we want, at least from a sync for a remote ---> local transfer or vice versa.

Not sure exactly what you will get on local ----> local.

Definitely worth double checking both.

On the compression front / deeper explanation front the FAQ for this entry can simply describe the process of doing this and point out the more detailed file transfer page we have.

To decide on whether we want it for cross cluster transfers, some empirical testing needed.

2023-01-12 11:59 UTC, nikishe commented on FAQs.rst
> +1. You want to copy the files to the new account on the same cluster node(e.g old account on Bessemer to new account on Bessemer), here we are only going to use the "avP" options as we dont need to c
The owner after the copy is the user of the location its getting copied to , so will not create conflicts. The preserved permissions are the chmod ones so 755/777. I might be wrong on this , so please correct me if i am , but from the documentation it handles directories without the -r.
@jkwmoore I was trying to avoid redundancies , so went with the option of linking the full documentation of the rsync/scp page from the "Transferring files" section.