Nextflow ShARC docs
rcgsheffield/sheffield_hpc pull request #1621
Opened 2023-01-13 15:56 UTC by Carldkennedy

First draft.

Any comments appreciated

2023-01-17 13:41 UTC, willfurnass commented
@markdunning Any comments/suggestions?

2023-01-17 17:38 UTC, markdunning commented
Apologies, I didn't get a chance yet. @lquayle88 might also be able to provide some input

2023-01-20 12:00 UTC, Lizzydapsy commented on sharc/software/apps/nextflow.rst
> +   :Nextflow pipelines: https://nf-co.re/
May be to point users directly to the pipelines as in https://nf-co.re/pipelines

2023-01-20 12:02 UTC, Lizzydapsy commented on sharc/software/apps/nextflow.rst
> +------------------
Installation notes should come after the test section, I think.

2023-01-20 12:05 UTC, jkwmoore commented on sharc/software/apps/nextflow.rst
> +------------------
Agree that ideally we give an example for them to run interactive and batch then installation notes go at the end and make reference to the previous section being how it was tested.

Think it is worth giving this test as said example.

2023-01-20 12:07 UTC, jkwmoore commented on sharc/software/apps/nextflow.rst
> +   :Nextflow pipelines: https://nf-co.re/
I think this may also be worth highlighting in the main text of the page too. Possibly with a hint block.

2023-01-20 12:19 UTC, Lizzydapsy commented on sharc/software/apps/nextflow.rst
> +  nextflow run tutorial.nf
It may be useful to include the dollar sign to denote code which should be executed from command line e.g 
$ nextflow run tutorial.nf

2023-01-20 12:20 UTC, Lizzydapsy reviewed
I have noted a few things I noticed. Feel free to ignore, they maynot be necessary.

2023-01-20 12:55 UTC, jkwmoore commented on sharc/software/apps/nextflow.rst
> +  nextflow run tutorial.nf
You can also apply emphasis to specific lines as so:  

``` 
.. code-block:: console
  :emphasize-lines: 1
  ```
  
  e.g.
  
  
![image](https://user-images.githubusercontent.com/69149348/213699868-f593f15c-0c24-4805-91e2-2c0b9a39cf2c.png)

2023-01-20 16:31 UTC, Carldkennedy commented on sharc/software/apps/nextflow.rst
> +  nextflow run tutorial.nf
Good ideas. Thank you both

2023-01-20 16:57 UTC, Carldkennedy commented on sharc/software/apps/nextflow.rst
> +------------------
Have added information about testing. Thank you both

2023-03-02 15:43 UTC, nikishe requested changes
Small changes

2023-03-02 15:43 UTC, nikishe commented on sharc/software/apps/nextflow.rst
> +:ref:`qrshx` or :ref:`qrsh` command.
```suggestion
:ref:`qrsh` or :ref:`qrshx` command. 
```

2023-03-02 15:43 UTC, nikishe commented on sharc/software/apps/nextflow.rst
> +:ref:`qrshx` or :ref:`qrsh` command.
It is correct , though I would personally omit qrshx umless there is a gui aspect to it

2023-03-02 15:43 UTC, nikishe commented on sharc/software/apps/nextflow.rst
> +Note: The module file also loads apps/java/11.0.2/binary
I am not sure you need this line, less is more

2023-03-02 15:43 UTC, nikishe commented on sharc/software/install_scripts/apps/nextflow/22.04.0/install_nextflow.sh
> +rm -r nextflow-22.04.0/ v22.04.0.tar.gz
Its perfect, but for future versions maybe add the code that builds the module file and stores it in the right place as well (Not an issue , just improvements on the next install)

2023-03-02 15:45 UTC, Carldkennedy commented on sharc/software/install_scripts/apps/nextflow/22.04.0/install_nextflow.sh
> +rm -r nextflow-22.04.0/ v22.04.0.tar.gz
Good idea. Thanks @nikishe

2023-03-02 15:45 UTC, Carldkennedy commented on sharc/software/apps/nextflow.rst
> +Note: The module file also loads apps/java/11.0.2/binary
Will remove. Thanks @nikishe

2023-03-02 15:48 UTC, jkwmoore commented on sharc/software/install_scripts/apps/nextflow/22.04.0/install_nextflow.sh
> +rm -r nextflow-22.04.0/ v22.04.0.tar.gz
Further to that, ideally we should keep the build directory and source files on system within the same area as the install so subsequent investigation of build settings / rebuild for whatever reason is more straightforward.

This could be be in the `/usr/local/media` area for source files if preferable.

2023-03-02 16:41 UTC, nikishe approved these changes

2023-03-02 16:45 UTC, merged