Add develpoment docs
rcgsheffield/sheffield_hpc pull request #1659
Opened 2023-03-14 13:31 UTC by Carldkennedy

Those modules which have been installed and are referenced up to this point have been added

2023-03-14 13:39 UTC, Carldkennedy commented
sbt, nvidia_compiler, PGI and clan not installed and not referenced so not adding for now

2023-03-14 13:44 UTC, Carldkennedy commented
Have commented out links to missing documentation with 
`.. sweep`

2023-03-14 13:46 UTC, willfurnass requested changes
Mostly LGTM

2023-03-14 13:46 UTC, willfurnass commented on stanagepilot/software/development/gcc.rst
> +   module load GCC/6.4.0-2.28    #part of the foss-2020a toolchain
Some comments wrong.  See https://docs.easybuild.io/common-toolchains/#common_toolchains_overview.

2023-03-14 13:46 UTC, willfurnass commented on stanagepilot/software/development/gcc.rst
> +   module load GCC/6.4.0-2.28    #part of the foss-2020a toolchain
Also, know why we have GCC < 8.2.0 (foss-2019a version) installed?

2023-03-14 13:46 UTC, willfurnass commented on stanagepilot/software/development/git.rst
> +And a newer version that can be activated by loading a module file and is only available on the worker nodes: ::
"only available on the worker nodes" -> not true

2023-03-14 13:46 UTC, willfurnass commented on stanagepilot/software/development/git.rst
> +Two version of git are available - an older version that is provided by the operating system and is available on both the login nodes and worker nodes: ::
```suggestion
Two version of git are available - an older version that is provided by the operating system: ::
```

2023-03-14 13:46 UTC, willfurnass commented on stanagepilot/software/development/git.rst
> +And a newer version that can be activated by loading a module file and is only available on the worker nodes: ::
```suggestion
And a newer version that can be activated by loading a module file: ::
```

2023-03-14 13:46 UTC, willfurnass commented on stanagepilot/software/development/git.rst
> +And a newer version that can be activated by loading a module file and is only available on the worker nodes: ::
NB we have other versions available that we need to delete.

2023-03-14 13:46 UTC, willfurnass commented on stanagepilot/software/development/git.rst
> +The git module has been installed using Easybuild 4.4.0 and a custom made git-2.39.2-GCCcore-10.3.0-nodocs.eb which can be found on system in the installation
4.4.0?  Suggest just omitting the EB version.

2023-03-14 13:46 UTC, willfurnass commented on stanagepilot/software/development/git.rst
> +directory: ``/usr/local/packages/live/eb/git/2.39.2-GCCcore-10.3.0-nodocs/easybuild``
Wrong path.

2023-03-14 13:46 UTC, willfurnass commented on stanagepilot/software/development/toolchains.rst
> +.. sweep
Suggest fleshing these out soon; the MPI docs in particular will be of use to many

2023-03-14 13:46 UTC, willfurnass commented on stanagepilot/software/development/toolchains.rst
> +- ``fosscuda``
Suggest commenting out mentions of `fosscuda` for now

2023-03-14 13:46 UTC, willfurnass commented on stanagepilot/software/development/toolchains.rst
> +.. sweep
Again, suggest fleshing out soon

2023-03-14 13:46 UTC, willfurnass commented on stanagepilot/software/development/toolchains.rst
> +See the `EasyBuild documentation for dependency versions for foss and intel <https://easybuild.readthedocs.io/en/latest/Common-toolchains.html#overview-of-common-toolchains>`__
```suggestion
See the `EasyBuild documentation for dependency versions for foss and intel <https://docs.easybuild.io/common-toolchains>`__
```

2023-03-14 13:46 UTC, willfurnass commented on stanagepilot/software/development/toolchains.rst
> +``fosscuda-2019a`` has the same dependencies as ``foss-2019a`` plus
Suggest comment out for now

2023-03-14 13:55 UTC, jkwmoore commented on stanagepilot/software/development/cmake.rst
> +   module load CMake/3.9.1-GCCcore-6.4.0   # compatible with foss-2018a toolchain
Only foss/2019b and onward is installed. Likewise we probably don't want people to be using the older toolchains so we may wish to omit those prior to 2020.

2023-03-14 14:04 UTC, jkwmoore commented on stanagepilot/software/development/cmake.rst
> +   module load CMake/3.11.4-GCCcore-7.3.0  # compatible with foss-2019b toolchain
When considering compatibility, what criteria are under consideration? Is it more sensible here that we indicate that the CMake versions should be loosely coupled with their matching GCCcore/GCC? (My expectation in terms of compatibility issues here is that GLIBC versioning may become a problem using a GCC major version too new.)

2023-03-14 14:06 UTC, jkwmoore commented on stanagepilot/software/development/cmake.rst
> +   module load CMake/3.11.4-GCCcore-7.3.0  # compatible with foss-2019b toolchain
Some further context on GCCcore here: https://github.com/easybuilders/easybuild-easyconfigs/issues/6366

2023-03-14 14:15 UTC, willfurnass commented on stanagepilot/software/development/cmake.rst
> +   module load CMake/3.11.4-GCCcore-7.3.0  # compatible with foss-2019b toolchain
If this affects Bessemer too then should be tracked as a separate Issue and addressed via a separate PR?

2023-03-14 14:15 UTC, jkwmoore commented on stanagepilot/software/development/cmake.rst
> +Usage of CMake often involves:
I think we may just want to provide a redirect here to the existing installation documentation at https://docs.hpc.shef.ac.uk/en/latest/hpc/installing-software.html#compiling-your-source-code-into-binaries and add some relevant info on usage of CMake there.

I expect this is worth filing an issue for, but not a priority at the moment.

2023-03-14 14:18 UTC, jkwmoore commented on stanagepilot/software/development/cmake.rst
> +   module load CMake/3.11.4-GCCcore-7.3.0  # compatible with foss-2019b toolchain
As it stands, the Bessemer documentation looks coherent on coupling with the toolchain GCC versioning so there's nothing to fix there.

That said I think a compromise here would be to make an import highlighting the importance of matching then, amend both pages at the same time with the import. That sounds like another PR.

2023-03-14 14:28 UTC, Carldkennedy commented on stanagepilot/software/development/git.rst
> +And a newer version that can be activated by loading a module file and is only available on the worker nodes: ::
Added a task on Jira STN-427

2023-03-14 14:28 UTC, Carldkennedy commented on stanagepilot/software/development/git.rst
> +Two version of git are available - an older version that is provided by the operating system and is available on both the login nodes and worker nodes: ::
Thank you, Will.

2023-03-14 14:37 UTC, jkwmoore commented on stanagepilot/software/development/git.rst
> +The git module has been installed using Easybuild 4.4.0 and a custom made git-2.39.2-GCCcore-10.3.0-nodocs.eb which can be found on system in the installation
That version is also not available on Stanage ;)

2023-03-14 14:42 UTC, Carldkennedy commented on stanagepilot/software/development/cmake.rst
> +Usage of CMake often involves:
Thanks, James. Added issue

2023-03-14 14:43 UTC, jkwmoore commented on stanagepilot/software/development/gcc.rst
> +   module load GCC/6.4.0-2.28    #part of the foss-2020a toolchain
Looking on system, GCC vers `GCC/6.4.0-2.28` and `GCC/7.3.0-2.30` look spurious. 

```
grep -r 'GCC/7.3.0-2.30' .
./staging/all/OpenBLAS/0.3.1-GCC-7.3.0-2.30.lua:if not ( isloaded("GCC/7.3.0-2.30") ) then
./staging/all/OpenBLAS/0.3.1-GCC-7.3.0-2.30.lua:    load("GCC/7.3.0-2.30")
./staging/all/GSL/2.5-GCC-7.3.0-2.30.lua:if not ( isloaded("GCC/7.3.0-2.30") ) then
./staging/all/GSL/2.5-GCC-7.3.0-2.30.lua:    load("GCC/7.3.0-2.30")
./staging/all/GCC/7.3.0-2.30.lua:local root = "/opt/apps/testapps/el7/software/staging/GCC/7.3.0-2.30"
```

```
grep -r 'GCC/6.4.0-2.28' .
./staging/all/GCC/6.4.0-2.28.lua:local root = "/opt/apps/testapps/el7/software/staging/GCC/6.4.0-2.28"
```

Recommend we remove these.

Looks like these toolchains will be needed as part of some of the older CUDA bits. So having these available in el7 is probably still a bit questionable:
```

grep -r 'GCC/8.2.0-2.31.1' .
./staging/all/CUDA/10.1.105-GCC-8.2.0-2.31.1.lua:if not ( isloaded("GCC/8.2.0-2.31.1") ) then
./staging/all/CUDA/10.1.105-GCC-8.2.0-2.31.1.lua:    load("GCC/8.2.0-2.31.1")
./staging/all/GCC/8.2.0-2.31.1.lua:local root = "/opt/apps/testapps/el7/software/staging/GCC/8.2.0-2.31.1"
./staging/all/gcccuda/2019a.lua:if not ( isloaded("GCC/8.2.0-2.31.1") ) then
./staging/all/gcccuda/2019a.lua:    load("GCC/8.2.0-2.31.1")
```

2023-03-14 14:44 UTC, Carldkennedy commented on stanagepilot/software/development/cmake.rst
> +   module load CMake/3.11.4-GCCcore-7.3.0  # compatible with foss-2019b toolchain
Added issue

2023-03-14 16:45 UTC, willfurnass commented on stanagepilot/software/development/gcc.rst
> +   module load GCC/6.4.0-2.28    #part of the foss-2020a toolchain
Because those CUDA/GPU-related builds aren't targeting the right microarch?  Yeah, agree.

2023-03-14 17:08 UTC, Carldkennedy commented on stanagepilot/software/development/toolchains.rst
> +.. sweep
Added jira STN-434

2023-03-14 17:11 UTC, Carldkennedy commented on stanagepilot/software/development/toolchains.rst
> +.. sweep
Added Jira STN-435

2023-03-21 09:10 UTC, nikishe reviewed
Just 2 suggestions , but looks good so far

2023-03-21 09:10 UTC, nikishe commented on stanagepilot/software/development/toolchains.rst
> +was installed using `EasyBuild <https://easybuild.readthedocs.io/>`__,
I think the easy build link that breaks down tool chains by versions  might be helpful here , or maybe even add the table yourself

2023-03-21 09:53 UTC, Carldkennedy commented on stanagepilot/software/development/toolchains.rst
> +was installed using `EasyBuild <https://easybuild.readthedocs.io/>`__,
Link is provided in next section

2023-03-21 10:35 UTC, Carldkennedy commented on stanagepilot/software/development/doxygen.rst
> +(and does) load the relevant :ref:`GCC compiler <gcc_stanage>` version.
Thank you, @nikishe. Rephrased

2023-03-21 10:45 UTC, nikishe approved these changes
LGTM

2023-03-21 10:52 UTC, Carldkennedy commented on stanagepilot/software/development/gcc.rst
> +   module load GCC/6.4.0-2.28    #part of the foss-2020a toolchain
Removed GCC/6.4.0-2.28, GCC/7.3.0-2.30 and OpenBLAS/0.3.1-GCC-7.3.0-2.30 from docs

2023-03-28 13:17 UTC, willfurnass commented on stanagepilot/software/parallel/impi.rst
> +   The Stanage cluster does not have a high performance interconnect between nodes. As
No, needs removing

2023-03-28 13:18 UTC, willfurnass commented on stanagepilot/software/parallel/impi.rst
> +    # Show which nodes you have been allocated CPU cores on
```suggestion
    # Show which node you have been allocated CPU cores on
```

2023-03-28 13:18 UTC, willfurnass commented on stanagepilot/software/parallel/impi.rst
> +supplied by Intel. An example of this using 2 cores is given below:
```suggestion
supplied by Intel. An example of this using 2 cores on one node is given below: 
```

2023-03-28 13:19 UTC, willfurnass commented on stanagepilot/software/parallel/impi.rst
> +    node051.pri.stanage.alces.network
Does not tally with what requested from Slurm

2023-03-28 13:31 UTC, willfurnass commented on stanagepilot/software/parallel/impi.rst
> +    MACHINEFILE="machinefile.$JOB_ID"
To show/confirm allocated nodes, tasks per node and CPUs per task you could instead just

```
echo "SLURM_JOB_NODELIST=${SLURM_JOB_NODELIST}"
echo "SLURM_NNODES=${SLURM_NNODES}"
echo "SLURM_NTASKS_PER_NODE=${SLURM_NTASKS_PER_NODE-1}"
echo "SLURM_CPUS_PER_TASK=${SLURM_CPUS_PER_TASK-1}"
``` 

Think this would be cleaner

2023-03-28 13:37 UTC, willfurnass commented on stanagepilot/software/parallel/openmpi.rst
> +    mpirun hello
Think we should propose using `srun --mpi=pmix_v4 --export=ALL` instead of `mpirun` but should also mention that using `mpirun` instead is still an option.

2023-03-28 13:38 UTC, willfurnass commented on stanagepilot/software/parallel/openmpi.rst
> +    srun --ntasks=4 --pty bash -i
May need `--mpi=pmix_v4` here - @jkwmoore ?

2023-03-28 13:50 UTC, willfurnass commented on stanagepilot/software/libs/index.rst
> +    blas
Currently results in a merge conflict.  as  `boost` and `proj` only listed in `HEAD` of `master`.  Suggest a rebase (or pull from `master`) to resolve.

2023-03-28 16:02 UTC, Carldkennedy commented on stanagepilot/software/libs/imkl.rst
> +   module load imkl/2022.2.1
I believe we're going to depreciate those modules. So leaving out of docs. If okay @willfurnass ?

2023-03-28 16:16 UTC, jkwmoore commented on stanagepilot/software/parallel/openmpi.rst
> +    srun --ntasks=4 --pty bash -i
Possibly, but at this stage (tested) I am fairly confident that we can have SLURM set the default to be pmix_v4 via the OpenMPI module files? 

If implemented it like that via the EB hooks and a module rebuild for OpenMPI modules, then that would need adding to the docs page too.

It also raises the same question for Intel MPI stuff.

2023-03-29 10:02 UTC, Carldkennedy commented on stanagepilot/software/libs/imkl.rst
> +   module load imkl/2022.2.1
Thanks @willfurnass.  Added fftw bits

2023-03-29 10:05 UTC, Carldkennedy commented on stanagepilot/software/parallel/impi.rst
> +    node051.pri.stanage.alces.network
I think in this case it is printing the node for each core. Will incorporate your suggestion below

2023-03-29 10:11 UTC, Carldkennedy commented on stanagepilot/software/parallel/openmpi.rst
> +    mpirun hello
@willfurnass , @jkwmoore commented we need to rebuild the OpenMPI module files to opinionate on {'SLURM_MPI_TYPE': "pmix_v4"}

2023-03-29 10:16 UTC, jkwmoore commented on stanagepilot/software/parallel/openmpi.rst
> +    mpirun hello
I am doing that as I write this, that in mind. With that set, we need to communicate at least in the administrator installation notes that this is the case. 

We should probably also highlight that automatic amendments to the installations are implemented via the hooks (including conditional logic for some parts based on versions.)

2023-03-29 10:36 UTC, Carldkennedy commented on stanagepilot/software/parallel/impi.rst
> +    MACHINEFILE="machinefile.$JOB_ID"
Agree. Thanks @willfurnass

2023-03-29 15:32 UTC, willfurnass reviewed
More comments on MPI bits

2023-03-29 15:32 UTC, willfurnass commented on stanagepilot/software/parallel/openmpi.rst
> +Maximum 64 cores can be requested.
I don't think this makes sense here.  Users can request more cores if they request multiple nodes.  Simplest option would be to omit this line.

2023-03-29 15:32 UTC, willfurnass commented on stanagepilot/software/libs/imkl.rst
> +   module load imkl/2022.2.1
Still looks like some toolchain versions missing for MKL.

2023-03-29 15:32 UTC, willfurnass commented on stanagepilot/software/parallel/impi.rst
> +supplied by Intel. An example of this using 2 cores on one node is given below:
```suggestion
supplied by Intel. An example of this using two single-core tasks on one node is given below: 
```

2023-03-29 15:32 UTC, willfurnass commented on stanagepilot/software/parallel/impi.rst
> +provided by Intel. An example of this using 2 cores is given below:
```suggestion
provided by Intel. An example of this using two single-core tasks on one node is given below:
```

2023-03-29 15:32 UTC, willfurnass commented on stanagepilot/software/parallel/openmpi.rst
> +This is an expected behaviour since we did not specify the number of CPU cores when requesting our interactive job.
```suggestion
This is an expected behaviour since by default interactive jobs get allocated one single-CPU-core task running on one node.
```

2023-03-29 15:34 UTC, willfurnass commented on stanagepilot/software/parallel/openmpi.rst
> +    module load OpenMPI/4.1.1-GCC-10.3.0  # part of the foss-2021a toolchain
Add warnings re the following performing poorly
*  OpenMPI/4.1.1-GCC-10.3.0
*  OpenMPI/4.1.1-GCC-11.2.0

Add to pages of things that depend on these too?

2023-03-29 15:36 UTC, willfurnass commented on stanagepilot/software/parallel/openmpi.rst
> +    Hello world from processor stanage-node003.shef.ac.uk, rank 3 out of 4 processors
Hostname will be `node003.pri.stanage.alces.network`, not `stanage-node003.shef.ac.uk`

2023-03-29 15:36 UTC, willfurnass commented on stanagepilot/software/parallel/openmpi.rst
> +    Hello world from processor stanage-node003.shef.ac.uk, rank 6 out of 8 processors
Hostname will be `node003.pri.stanage.alces.network`, not `stanage-node003.shef.ac.uk`

2023-03-29 15:36 UTC, willfurnass commented on stanagepilot/software/parallel/openmpi.rst
> +    Hello world from processor stanage-node001.shef.ac.uk, rank 0 out of 1 processors
Hostname will be `node001.pri.stanage.alces.network`, not `stanage-node001.shef.ac.uk`

2023-03-29 15:38 UTC, willfurnass commented on stanagepilot/software/libs/imkl.rst
> +   module load imkl/2022.1.0
```suggestion
   module load imkl/2022.1.0 # part of intel-2022a EasyBuild toolchain
```

2023-03-29 15:39 UTC, willfurnass commented on stanagepilot/software/libs/imkl.rst
> +   module load imkl/2022.2.1
```suggestion
   module load imkl/2022.2.1 # part of intel-2022b EasyBuild toolchain
```

2023-03-29 16:05 UTC, Carldkennedy commented on stanagepilot/software/parallel/openmpi.rst
> +    module load OpenMPI/4.1.1-GCC-10.3.0  # part of the foss-2021a toolchain
`OpenMPI/4.1.1-GCC-10.3.0
 foss/2021a
 gompi/2021a
 ScaLAPACK/2.1.0-gompi-2021a-fb
 foss/2021a
 FFTW/3.3.9-gompi-2021a
 foss/2021a

OpenMPI/4.1.1-GCC-11.2.0
 foss/2021b
 SciPy-bundle/2021.10-foss-2021b
 GDAL/3.3.2-foss-2021b
 networkx/2.6.3-foss-2021b
 HPL/2.3-foss-2021b
 GDAL/3.3.2-foss-2021b
 networkx/2.6.3-foss-2021b
 gompi/2021b
 ScaLAPACK/2.1.0-gompi-2021b-fb
 foss/2021b
 SciPy-bundle/2021.10-foss-2021b
 GDAL/3.3.2-foss-2021b
 networkx/2.6.3-foss-2021b
 HPL/2.3-foss-2021b
 GDAL/3.3.2-foss-2021b
 networkx/2.6.3-foss-2021b
 HDF5/1.12.1-gompi-2021b
 GDAL/3.3.2-foss-2021b
 netCDF/4.8.1-gompi-2021b
 GDAL/3.3.2-foss-2021b
 FFTW/3.3.10-gompi-2021b
 foss/2021b
 SciPy-bundle/2021.10-foss-2021b
 GDAL/3.3.2-foss-2021b
 networkx/2.6.3-foss-2021b
 HPL/2.3-foss-2021b
 GDAL/3.3.2-foss-2021b
 networkx/2.6.3-foss-2021b
 netCDF/4.8.1-gompi-2021b
 GDAL/3.3.2-foss-2021b

`

2023-03-29 16:06 UTC, willfurnass commented on stanagepilot/software/parallel/impi.rst
> +    module load impi/2018.5.288-iccifort-2019.5.281     # subset of the intel 2019b toolchain
intel-2019a and intel-2019b's IMPI perform badly when invoked with srun (but not with mpirun).

2023-03-29 16:06 UTC, willfurnass commented on stanagepilot/software/parallel/impi.rst
> +    module load impi/2018.5.288-iccifort-2019.5.281     # subset of the intel 2019b toolchain
Need to document

2023-03-29 16:13 UTC, Carldkennedy commented on stanagepilot/software/parallel/openmpi.rst
> +    Hello world from processor stanage-node001.shef.ac.uk, rank 0 out of 1 processors
Thank you @willfurnass

2023-03-30 09:22 UTC, jkwmoore commented on stanagepilot/software/parallel/impi.rst
> +    module load impi/2018.5.288-iccifort-2019.5.281     # subset of the intel 2019b toolchain
I'm leaning more in favour of installing only intel-2020a and onward for this given the peculiarities of the Intel MPI 2018 packages that are within intel-2019x.

2023-03-30 09:54 UTC, Carldkennedy commented on stanagepilot/software/parallel/impi.rst
> +    module load impi/2018.5.288-iccifort-2019.5.281     # subset of the intel 2019b toolchain
Reverse dependencies: 
```
impi/2018.4.274-iccifort-2019.1.144-GCC-8.2.0-2.31.1
 intel/2019a
 iimpi/2019a
 imkl/2019.1.144-iimpi-2019a
 intel/2019a
impi/2018.5.288-iccifort-2019.5.281
 intel/2019b
 iimpi/2019b
 HDF5/1.10.5-iimpi-2019b
 imkl/2019.5.281-iimpi-2019b
 intel/2019b

2023-03-30 09:54 UTC, willfurnass commented on stanagepilot/software/parallel/impi.rst
> +    module load impi/2018.5.288-iccifort-2019.5.281     # subset of the intel 2019b toolchain
@desmfryan What are the implications for Abaqus users?

2023-03-30 10:03 UTC, jkwmoore commented on stanagepilot/software/parallel/impi.rst
> +    module load impi/2018.5.288-iccifort-2019.5.281     # subset of the intel 2019b toolchain
None iirc - ABAQUS doesn't have any external dependency on Intel MPI? Though any user defined functions would require a matched intel compiler.

2023-03-30 13:07 UTC, Carldkennedy commented on stanagepilot/software/libs/index.rst
> +    blas
Fixed. Thank you, Will.

2023-03-30 13:19 UTC, Carldkennedy commented on stanagepilot/software/parallel/openmpi.rst
> +    module load OpenMPI/4.1.1-GCC-10.3.0  # part of the foss-2021a toolchain
Warning added to OpenMPI. Add warnings to others in a seperate PR? @willfurnass

2023-04-03 16:07 UTC, nikishe approved these changes
LGTM though "and investigations are ongoing" feels no end it sight. Though this is a personal preference to a correct statement.

2023-04-03 16:09 UTC, nikishe requested changes
The affected toolchains include ``foss-2021a``, ``foss-2021b``, ``gompi-2021a``, and ``gompi-2021b``.

2023-04-04 12:20 UTC, nikishe approved these changes

2023-04-04 12:54 UTC, merged