Stanage A100 GPU nodes: first cuDNN install
rcgsheffield/sheffield_hpc pull request #1670
Opened 2023-03-28 15:33 UTC by willfurnass

2023-03-28 17:06 UTC, ptheywood commented on stanagepilot/software/libs/cuda.rst
> +Profiling using nvprof
`nvprof` is not supported on SM80+ devices (i.e. all present in Stanage), so either a simple sentence stating it is not supported and to use `nsys`/`ncu`, or just remove the section. 

> Visual Profiler and nvprof don’t support devices with compute capability 8.0 and higher. Next-gen tools NVIDIA Nsight Compute and NVIDIA Nsight Systems should be used instead.

[source: `CUDA Profilers User Guide: Profiler changes in CUDA 11.0`](https://docs.nvidia.com/cuda/profiler-users-guide/#changelog)

2023-03-28 17:19 UTC, ptheywood commented on stanagepilot/gpu-computing.rst
> +The above will give you 2GB more CPU RAM than the 40GB of GPU RAM available on the NVIDIA A100.
```suggestion
.. code-block:: sh

   # NB Each NVIDIA A100 GPU has 80GB of RAM
   srun --partition=gpu --gres=gpu:1 --mem=82G --pty bash

The above will give you 2GB more CPU RAM than the 80GB of GPU RAM available on the NVIDIA A100.
```

An old nvidia-smi log has the GPUs as being the 80GiB variant `NVIDIA A100-SXM4-80GB`, `0MiB / 81920MiB`

2023-03-28 17:25 UTC, ptheywood commented on stanagepilot/software/libs/cuda.rst
> +   nvcc filename.cu \
This is correct, but will only work with CUDA >= 11.0 which introdcued SM 80. 

[CUDA 11.0 Release Notes] (https://docs.nvidia.com/cuda/archive/11.0_GA/cuda-toolkit-release-notes/index.html#cuda-general-new-features).

So may need to add a condition around that (if CUDA 10.x is avialable as suggested in `Compiling the sample programs`), where embedding PTX for 70 via `-gencode=arch=compute_70,code=compute_70` would be the closest fit (but ideally everyone should use CUDA 11.0+ on these nodes).

2023-03-28 17:28 UTC, ptheywood commented on stanagepilot/software/libs/cudnn.rst
> +.. See** :ref:`GPUComputing_bessemer` **for more information on how to request a GPU-enabled node for an interactive session or job submission.**
```suggestion
.. See** :ref:`gpu_computing_stanage` **for more information on how to request a GPU-enabled node for an interactive session or job submission.**
```

I think that's the right xref.

2023-03-29 08:42 UTC, willfurnass commented on stanagepilot/gpu-computing.rst
> +The above will give you 2GB more CPU RAM than the 40GB of GPU RAM available on the NVIDIA A100.
Doh!  I'd even mentioned they were the 80GB versions in an addition to the stanage-specs.rst page

2023-03-30 12:25 UTC, jkwmoore commented on stanagepilot/software/libs/cudnn.rst
> +   :Documentation: https://developer.nvidia.com/cudnn
Far as I can tell, these links are a muchness of a muchness and reference more or less the same content and have the same linkages.

>Or are we avoiding breaking links if structure changes in future?

I don't think I have enough info to know if that is the case but I wouldn't expect either link to get deleted by nvidia any time soon.

2023-03-30 12:30 UTC, willfurnass commented on stanagepilot/software/libs/cudnn.rst
> +   :Documentation: https://developer.nvidia.com/cudnn
Seems https://developer.nvidia.com/cudnn now redirects to https://developer.nvidia.com so  I've switched to using the URL Carl found.

2023-03-30 12:30 UTC, willfurnass commented on stanagepilot/software/libs/cudnn.rst
> +   :URL: https://developer.nvidia.com/cudnn
```suggestion
   :URL: https://docs.nvidia.com/cudnn
```

2023-03-30 12:34 UTC, willfurnass commented on stanagepilot/software/libs/cudnn.rst
> +   :Documentation: https://developer.nvidia.com/cudnn
Huh, you're right.  Dunno what happened earlier.  Reverted.

2023-03-30 12:36 UTC, jkwmoore commented on stanagepilot/software/development/index.rst
>          :maxdepth: 1
Might be time to enable this bit as the toctree?

2023-03-30 12:37 UTC, jkwmoore commented on stanagepilot/software/development/index.rst
>          :maxdepth: 1
i.e. LN14 - 21

2023-04-04 15:53 UTC, jkwmoore requested changes
Added some suggestions - hopefully they're visible now.

2023-04-04 16:01 UTC, merged