Amend stanage /scratch info.
rcgsheffield/sheffield_hpc pull request #1743
Opened 2023-04-20 10:54 UTC by jkwmoore

Update pending on STA98: Per-job $TMPDIR to be completed.

The directory format may need updating if my guess is incorrect. Please don't merge without a double check on it after STA98 is complete!

2023-04-20 11:04 UTC, willfurnass requested changes

2023-04-20 11:04 UTC, willfurnass commented on hpc/filestore.rst
> +    The scheduler will automatically create a per-job directory for you under ``/scratch``.
```suggestion
    The scheduler will automatically create a per-job directory for you under ``/tmp``.
```

2023-04-20 11:06 UTC, jkwmoore commented on hpc/filestore.rst
> +    The scheduler will automatically create a per-job directory for you under ``/scratch``.
Ah I forgot to hit save again before commit. My bad.

2023-04-21 07:33 UTC, jkwmoore commented on hpc/filestore.rst
> +      /tmp/2660172
```suggestion
      /tmp/job.2660172
```

2023-04-21 07:35 UTC, merged