Update OpenFOAM Stanage
rcgsheffield/sheffield_hpc pull request #1775
Opened 2023-05-03 12:48 UTC by Carldkennedy

2023-05-03 12:50 UTC, willfurnass approved these changes

2023-05-03 12:53 UTC, jkwmoore commented on stanage/software/apps/openfoam.rst
> +   :Dependencies: Easybuild foss/2022a toolchain see :ref:`stanage_eb_toolchains`
Foss 2022a, 2020a and 2020b here, should we just call it Easybuild foss?

Not for this PR but I also think our development toolchains page needs a bit of work.

2023-05-03 12:54 UTC, jkwmoore requested changes
Pending changes on line 9 and the tests on system confirming it work being complete. LGTM.

2023-05-03 12:59 UTC, jkwmoore commented on stanage/software/apps/openfoam.rst
> +   :Dependencies: Easybuild foss/2020a, 2020b and 2022a toolchains see :ref:`stanage_eb_toolchains`
I was more getting at: 
```suggestion
   :Dependencies: Easybuild foss toolchain see :ref:`stanage_eb_toolchains`
```

2023-05-03 12:59 UTC, willfurnass commented on stanage/software/apps/openfoam.rst
> +   :Dependencies: Easybuild foss/2022a toolchain see :ref:`stanage_eb_toolchains`
Think I agree with @jkwmoore 's suggestion here.

2023-05-03 13:00 UTC, willfurnass commented on stanage/software/apps/openfoam.rst
> +   :Dependencies: Easybuild foss/2020a, 2020b and 2022a toolchains see :ref:`stanage_eb_toolchains`
Do we still want to mention NCurses, METIS, SCOTCH, CGAL and Paraview if they're all run-time dependencies?

2023-05-03 13:03 UTC, jkwmoore commented on stanage/software/apps/openfoam.rst
> +   :Dependencies: Easybuild foss/2020a, 2020b and 2022a toolchains see :ref:`stanage_eb_toolchains`
Some of these (METIS, SCOTCH, CGAL) will be depending on what code you invoke so it very well might be worth outright telegraphing that people can check them with a module load or inspecting the Easyconfig.

iirc Paraview is just wrapped in Parafoam with some workflow bits to help out but I might be wrong. Not sure on NCurses, but I expect it is also runtime depd.

2023-05-03 13:05 UTC, jkwmoore commented on stanage/software/apps/openfoam.rst
> +   :Dependencies: Easybuild foss/2020a, 2020b and 2022a toolchains see :ref:`stanage_eb_toolchains`
In a general sense I think we might need to do more to assist users in figuring out dependencies for Easybuild/modules software and I put some effort into the modules page not so long ago around that.

We may want to generate a short importable section with the crib notes of how to check this for dependency heavy software / modules like this.

2023-05-03 13:20 UTC, Carldkennedy commented
All examples in docs completed successfully

2023-05-10 16:36 UTC, jkwmoore approved these changes

2023-05-10 16:37 UTC, merged