1781 document lammps on stanage
rcgsheffield/sheffield_hpc pull request #1783
Opened 2023-05-05 11:23 UTC by Carldkennedy

Also updating ShARC LAMMPS docs

2023-05-09 16:23 UTC, jkwmoore commented on stanage/software/apps/lammps.rst
> +   #SBATCH --nodes=1
```suggestion
```

2023-05-10 11:36 UTC, Carldkennedy commented on stanage/software/apps/lammps.rst
> +   #SBATCH --nodes=1
Added note. Thanks @jkwmoore

2023-05-10 13:35 UTC, nikishe reviewed
LGTM.

2023-05-10 15:42 UTC, jkwmoore commented on stanage/software/apps/lammps.rst
> +   cp /opt/apps/testapps/el7/software/staging/LAMMPS/3Mar2020-intel-2020a-Python-3.8.2-kokkos/examples/indent/in.indent .
Can this be amended to use the ``$EBROOTLAMMPS`` path, to so this won't need further amendment when we port the area and / or staging --> live.

2023-05-10 15:45 UTC, jkwmoore commented on stanage/software/apps/lammps.rst
> +   cp /opt/apps/testapps/el7/software/staging/LAMMPS/3Mar2020-intel-2020a-Python-3.8.2-kokkos/examples/indent/in.indent .
```EBROOTLAMMPS=/opt/apps/testapps/el7/software/staging/LAMMPS/3Mar2020-foss-2020a-Python-3.8.2-kokkos```

2023-05-10 15:48 UTC, jkwmoore requested changes
LGTM pending an amendment of the path I commented on. For future PRs, if we can keep corrections existing modules in another PR that'd be grand (makes for a more coherent commit log.)

2023-05-11 07:26 UTC, Carldkennedy commented on stanage/software/apps/lammps.rst
> +   cp /opt/apps/testapps/el7/software/staging/LAMMPS/3Mar2020-intel-2020a-Python-3.8.2-kokkos/examples/indent/in.indent .
Perfect. Thanks @jkwmoore

2023-05-11 11:01 UTC, jkwmoore approved these changes

2023-05-17 08:45 UTC, nikishe approved these changes

2023-05-17 08:46 UTC, merged