Add fosscuda toolchains back
rcgsheffield/sheffield_hpc pull request #1794
Opened 2023-05-11 11:40 UTC by Carldkennedy

2023-05-11 11:42 UTC, nikishe reviewed
LGTM

2023-05-11 12:58 UTC, willfurnass commented
`fosscuda` not installed at present? 

Suggest we only install more in the way of older CUDA tooling if we really need to.  Folks will get best perf if they adopt CUDA >= 11 to make best use of the A100s and >= 11.8 to make best use of the H100s.

2023-05-12 08:19 UTC, Carldkennedy commented
> `fosscuda` not installed at present?
> 
> Suggest we only install more in the way of older CUDA tooling if we really need to. Folks will get best perf if they adopt CUDA >= 11 to make best use of the A100s and >= 11.8 to make best use of the H100s.

You're right @willfurnass, not installed. I'll remove those sections.

2023-05-12 08:50 UTC, jkwmoore commented on stanage/software/development/toolchains.rst
> +The two supported toolchains on Stanage are:
Should this really be "The two main toolchains 'with support|available' on Stanage are" ? Is this support from us or just availability on the cluster?

If we mean availability we should say that instead I think.

2023-05-12 08:52 UTC, jkwmoore requested changes
LGTM - we may just want to decide on whether the suggested amendment is needed.

2023-05-12 08:56 UTC, nikishe approved these changes
LGTM (Post jame's suggestion)

2023-05-12 09:10 UTC, Carldkennedy commented on stanage/software/development/toolchains.rst
> +The two supported toolchains on Stanage are:
The two main toolchains available with support on Stanage are: ?

2023-05-12 09:29 UTC, jkwmoore commented on stanage/software/development/toolchains.rst
> +The two supported toolchains on Stanage are:
Well I suppose it depends mainly on whether you fellas want to explicitly say you will support those toolchains, if yes, how? The latest 2 years worth etc...

I'm not averse to saying their available but at some point we want to explicitly declare our intentions in terms of EB toolchain support formally.

This page seems like the sensible place?

2023-05-15 10:47 UTC, willfurnass commented on stanage/software/development/toolchains.rst
> +The two supported toolchains on Stanage are:
Suggest getting this merged and revisiting this conversation via separate Issue/PR.

2023-05-15 10:54 UTC, merged