Add global warning and info page for ShARC decommissioning.
rcgsheffield/sheffield_hpc pull request #1830
Opened 2023-07-04 16:58 UTC by jkwmoore

Merge pending on approval / a comms email being developed.

Comms email should include the ' information on issues that impede migration from ShARC to Stanage' Google form which is being omitted from public viewing here.

2023-07-05 14:11 UTC, desmfryan commented
Looks good to me James

2023-07-05 14:35 UTC, nikishe approved these changes
LGTM

2023-07-10 12:41 UTC, Carldkennedy approved these changes
LGTM

2023-07-12 11:22 UTC, jkwmoore commented on sharc/sharc-decommissioning.rst
> +Once ShARC has been decommissioned and all data securely deleted the system is to be donated to the `Taras Shevchenko National University of Kyiv <http://www.univ.kiev.ua/en/>`_.
This is incorrect and needs amendment to: 

```suggestion
Once ShARC has been decommissioned and all data securely deleted the system is to be donated to the `Igor Sikorsky Kyiv Polytechnic Institute <https://kpi.ua/en>`_ in Kyiv, Ukraine.
```

2023-07-20 09:28 UTC, willfurnass requested changes

2023-07-20 09:28 UTC, willfurnass commented on sharc/sharc-decommissioning.rst
> +As Bessemer only permits single node execution and has approximately 18 months of life left, we recommend that ShARC users preferentially migrate workloads to Stanage instead.
```suggestion
As Bessemer only permits single node execution and is several years older than Stanage, we recommend that ShARC users preferentially migrate workloads to Stanage instead.
```

2023-07-20 09:55 UTC, willfurnass approved these changes

2023-07-20 09:55 UTC, merged