Add Slurm sattach info
rcgsheffield/sheffield_hpc pull request #1941
Opened 2024-01-04 10:14 UTC by Carldkennedy

2024-01-04 10:48 UTC, jkwmoore commented on hpc/scheduler/index.rst
> +Just keep in mind that ``sattach`` doesn't work for external or batch steps, as their input and output channels aren't
```suggestion
Just keep in mind that ``sattach`` doesn't work for external or batch steps, as they aren't 
```

2024-01-04 10:49 UTC, jkwmoore commented on hpc/scheduler/index.rst
> +Just keep in mind that ``sattach`` doesn't work for external or batch steps, as their input and output channels aren't
```suggestion
Just keep in mind that ``sattach`` doesn't work for external or batch steps, as they aren't 
```

2024-01-04 10:50 UTC, jkwmoore requested changes
Besides my comments for a slight simplification of the warning about different job step types LGTM.

If happy with my suggestions, please merge with them.

2024-01-04 11:46 UTC, willfurnass commented
Could we have just one section for both clusters?  The content is effectively the same.

2024-01-04 11:48 UTC, jkwmoore commented
Agree that would be ideal, but as it stands that would need a large refactor of the bulk of the page (which is needed at some point.)

2024-01-04 12:11 UTC, willfurnass commented
That's the kind of rebuttal I normally give you!  Fair point; let's refactor separately.

2024-01-04 12:16 UTC, merged

2024-01-05 08:52 UTC, nikishe commented on hpc/scheduler/index.rst
> +If we lose connection to an interactive job, we can use the ``sattach`` command which attaches to a running Slurm job step.
Change "we" to "you" for consistency

2024-01-05 08:52 UTC, nikishe commented on hpc/scheduler/index.rst
> +If we lose connection to an interactive job, we can use the ``sattach`` command which attaches to a running Slurm job step.
Change "we" to "you" for consistency