srun jobID docs
rcgsheffield/sheffield_hpc pull request #1945
Opened 2024-01-05 15:03 UTC by nikishe

2024-01-10 10:14 UTC, willfurnass commented on hpc/scheduler/advanced_job_analysis_and _profiling.rst
> +    squeue --user=$USER
```suggestion
    squeue --me
```

2024-01-10 10:15 UTC, jkwmoore commented on hpc/scheduler/advanced_job_analysis_and _profiling.rst
> +    squeue --user=$USER
Agree with this, I believe we also have quite a lot of the same change to make in the job submission pages.

Will look at this now.

2024-01-10 10:27 UTC, willfurnass requested changes
Mostly looks good!  A few wording suggestions (and some grammatical pedantry).

2024-01-10 10:27 UTC, willfurnass commented on hpc/scheduler/advanced_job_analysis_and _profiling.rst
> +Accessing A Running Multi Node Slurm Batch job
```suggestion
Accessing A Running Multi-Node Slurm Batch job
```

2024-01-10 10:27 UTC, willfurnass commented on hpc/scheduler/advanced_job_analysis_and _profiling.rst
> +In the scenario you are running a multi node slurm job you can use ``squeue`` to see the nodes your job is using:
```suggestion
In the scenario you are running a multi-node Slurm job you can use ``squeue`` to see the nodes your job is using:
```

2024-01-10 10:27 UTC, willfurnass commented on hpc/scheduler/advanced_job_analysis_and _profiling.rst
> +    squeue --user=$USER
```suggestion
    squeue --me
```

2024-01-10 10:27 UTC, willfurnass commented on hpc/scheduler/advanced_job_analysis_and _profiling.rst
> +Accessing A Running Single Node Slurm Batch job
```suggestion
Accessing A Running Single-Node Slurm Batch job
```

2024-01-10 10:27 UTC, willfurnass commented on hpc/scheduler/advanced_job_analysis_and _profiling.rst
> +In some cases, you might want to access the resources of an existing scheduler allocation, for example a single node batch job that is in the running state. After allocating resources with ``sbatch``
How about this instead?

```suggestion
In some cases, you might want to interact with a batch job in the ``RUNNING``  state (e.g. for fault-finding, debugging or profiling purposes).  You can start an interactive session within the resource allocation (memory and CPU cores on particular nodes) associated with the job with:
```

2024-01-10 10:27 UTC, willfurnass commented on hpc/scheduler/advanced_job_analysis_and _profiling.rst
> +The command creates a new job step and starts interactive bash shell session within a previously allocated job, allowing you to interact with the resources allocated to that job.
```suggestion
The command creates a new Job Step in the batch job with ID ``<JOBID>`` and starts interactive bash shell session within a that Job Step, allowing you to interact with the resources allocated to that job.
```

2024-01-10 10:27 UTC, willfurnass commented on hpc/scheduler/advanced_job_analysis_and _profiling.rst
> +If all the allocated CPU resources are already used, srun will prohibit the new job step the access to the resources. However, the argument ``--overlap`` can be passed to srun to allow job steps to o
```suggestion
If all the allocated CPU resources are already used, ``srun`` will prohibit the new Job Step the access to the resources. However, the argument ``--overlap`` can be passed to ``srun`` to allow Job Steps to overlap on the resources.
```

2024-01-10 10:27 UTC, willfurnass commented on hpc/scheduler/advanced_job_analysis_and _profiling.rst
> +start profiling and analysing the perfomance of the node and the job by using commands such as:
```suggestion
Start profiling and analysing the perfomance of the node and the job by using commands such as:
```

2024-01-10 10:27 UTC, willfurnass commented on hpc/scheduler/advanced_job_analysis_and _profiling.rst
> +The command creates a new job step and starts interactive bash shell session within a previously allocated job, allowing you to interact with the resources allocated to that job.
Also, do we want to link to reference info that explains what a Job Step is?

2024-01-15 13:46 UTC, Carldkennedy reviewed
A few minor suggestions. Otherwise LGTM

2024-01-15 13:46 UTC, Carldkennedy commented on hpc/scheduler/advanced_job_analysis_and _profiling.rst
> +Accessing A Running Single-Node Slurm Batch job
```suggestion
Accessing a Running Single-Node Slurm Batch job
```

2024-01-15 13:46 UTC, Carldkennedy commented on hpc/scheduler/advanced_job_analysis_and _profiling.rst
> +The command creates a new Job Step in the batch job with ID ``<JOBID>`` and starts interactive bash shell session within a that Job Step, allowing you to interact with the resources allocated to that
```suggestion
The command creates a new Job Step in the batch job with ID ``<JOBID>`` and starts an interactive bash shell session within that Job Step, allowing you to interact with the resources allocated to that job.
```

2024-01-15 13:46 UTC, Carldkennedy commented on hpc/scheduler/advanced_job_analysis_and _profiling.rst
> +If all the allocated CPU resources are already used, ``srun`` will prohibit the new Job Step the access to the resources. However, the argument ``--overlap`` can be passed to ``srun`` to allow Job St
```suggestion
If all the allocated CPU resources are already used, ``srun`` will prohibit the new Job Step to access those resources. However, the argument ``--overlap`` can be passed to ``srun`` to allow Job Steps to share those resources.
```

2024-01-15 13:46 UTC, Carldkennedy commented on hpc/scheduler/advanced_job_analysis_and _profiling.rst
> +Accessing A Running Multi-Node Slurm Batch job
```suggestion
Accessing a Running Multi-Node Slurm Batch job
```

2024-01-15 14:02 UTC, Carldkennedy approved these changes
LGTM

2024-01-19 09:35 UTC, merged