Removing sharc mentions
rcgsheffield/sheffield_hpc pull request #1946
Opened 2024-01-08 12:50 UTC by Carldkennedy

PR to remove most mentions of ShARC. 
Another PR will move some to decommissioned section.

2024-01-10 13:20 UTC, Carldkennedy commented on hpc/transferring-files.rst
> +* Use a :ref:`flight session <flight-desktop>` on Stanage or   to open firefox and interactively download directly to clusters.
```suggestion
* Open a Firefox browser and interactively download directly to clusters. Using a :ref:`flight session <flight-desktop>` on Stanage or interactive session on Bessemer 
```

2024-01-10 13:24 UTC, Carldkennedy commented on hpc/transferring-files.rst
> +* Open a Firefox browser and interactively download directly to clusters. Using a :ref:`flight session <flight-desktop>` on Stanage or interactive session on Bessemer
New Firefox section to replace qsh-vis section in another PR

2024-01-10 17:21 UTC, Carldkennedy commented on bessemer/software/parallel/impi.rst
> +   should be run on the Stanage cluster for the reason above.
Makes much more sense @willfurnass. Amended

2024-01-11 11:00 UTC, nikishe requested changes
Really good work carl. Just 2 notes

2024-01-11 11:21 UTC, Carldkennedy commented on hpc/transferring-files.rst
> +* Open a Firefox browser and interactively download directly to clusters. Using a :ref:`flight session <flight-desktop>` on Stanage or interactive session on Bessemer
Thank you @nikishe. Amended.

2024-01-11 11:32 UTC, Carldkennedy commented on hpc/connecting.rst
> +There are icons for Bessemer and ShARC Applications. However, ShARC was decommissioned hence those applications are no longer available.
Agree if icons are scheduled to be removed in the near future. Otherwise suggest we keep as is for now. @willfurnass @jkwmoore

2024-01-11 13:36 UTC, nikishe requested changes
Only a one change . And then should pass

2024-01-11 13:36 UTC, nikishe commented on hpc/filestore.rst
> +They are are **faster** than :ref:`home_dir` and :ref:`shared_dir` when dealing with larger files but
```suggestion
They are **faster** than :ref:`home_dir` and :ref:`shared_dir` when dealing with larger files but 
```

2024-01-11 13:39 UTC, nikishe approved these changes

2024-01-11 13:45 UTC, merged