Remove or move ShARC from FAQ
rcgsheffield/sheffield_hpc pull request #1948
Opened 2024-01-09 14:58 UTC by Carldkennedy

Removed ShARC references from FAQ
Moved sections entirely related to ShARC to decommissioned section.

2024-01-10 10:43 UTC, jkwmoore commented on FAQs.rst
> +additionally the grace period indicates the grace period for exceeding the soft quota has expired.
Might be worth tabbing this section between Stanage and Bessemer given the different quota command behaviours?

2024-01-10 10:45 UTC, jkwmoore commented on FAQs.rst
> +You can request more than this when running your ``srun`` command.
iirc, Bessemer defaults to 2G and Stanage to 4016MB.

2024-01-10 10:49 UTC, jkwmoore commented on FAQs.rst
> +2. You want to copy your files to the new account on a different cluster node(e.g old account on Bessemer to new account on Stanage), here we are going to use the option "avzP" as we are going to tra
We might want to amend "over the internet" to be a bit more specific. Bessemer / Stanage remote links are over JISC link / private link.

2024-01-10 11:22 UTC, Carldkennedy commented on FAQs.rst
> +2. You want to copy your files to the new account on a different cluster node(e.g old account on Bessemer to new account on Stanage), here we are going to use the option "avzP" as we are going to tra
Thank you @jkwmoore. New commit to reflect your suggestions

2024-01-10 14:42 UTC, willfurnass commented on decommissioned/sharc/FAQ_sharc.rst
> +'Illegal Instruction' errors
NB users may encounter this issue on Stanage if they make an optimised build of a program or lib on an Icelake node then  try running it on a Milan node (or vice versa)

2024-01-10 14:45 UTC, willfurnass approved these changes
Minor changes suggested

2024-01-10 14:45 UTC, willfurnass commented on FAQs.rst
> +2. You want to copy your files to the new account on a different cluster node(e.g old account on Bessemer to new account on Stanage), here we are going to use the option "avzP" as we are going to tra
```suggestion
2. You want to copy your files to the new account on a different cluster node (e.g old account on Bessemer to new account on Stanage), here we are going to use the option `avzP` as we are going to transfer data over the JANET link (Bessemer) and private leased link (Stanage), and it will be faster if it is compressed.
```

2024-01-10 14:45 UTC, willfurnass commented on FAQs.rst
> +By default, an interactive session on Stanage provides you with 4016MB of RAM (sometimes called real memory) or on Bessemer with 2 Gigabytes of RAM.
```suggestion
By default, an interactive session on Stanage provides you with 4016 MB of memory or on Bessemer with 2 GB (2048 MB) of memory.
```

2024-01-10 17:09 UTC, Carldkennedy commented on decommissioned/sharc/FAQ_sharc.rst
> +'Illegal Instruction' errors
Added an edited version back into FAQ

2024-01-11 13:36 UTC, willfurnass requested changes
Sorry, suggested quite a few changes here.

2024-01-11 13:36 UTC, willfurnass commented on FAQs.rst
> +If you get this error **after copying compiled programs onto a cluster** then you may need to recompile them on the cluster or recompile them elsewhere without aggressively optimising for processor a
'on' instead of 'onto'?

2024-01-11 13:36 UTC, willfurnass commented on FAQs.rst
> +If your program fails with an **Illegal Instruction** error then it may have been compiled using (and optimised for) one type of processor but is running on another.
Could provide examples? 
* compiled on one generation of Intel CPU but run on an older or newer generation
* compiled on an AMD CPU but run on Intel CPU

2024-01-11 13:36 UTC, willfurnass commented on FAQs.rst
> +If you get this error **after copying compiled programs onto a cluster** then you may need to recompile them on the cluster or recompile them elsewhere without aggressively optimising for processor a
The issue isn't which cluster(s) a program was compiled then run on; the issue is the CPU architectures an executable (or library) was compiled for and run on.

2024-01-11 13:36 UTC, willfurnass commented on FAQs.rst
> +If you get this error **after copying compiled programs onto a cluster** then you may need to recompile them on the cluster or recompile them elsewhere without aggressively optimising for processor a
> on the cluster or recompile them elsewhere without aggressively optimising for processor architecture.

I suggest omitting this as we don't want to encourage it.

2024-01-11 13:36 UTC, willfurnass commented on FAQs.rst
> +Bessemer has the same architecture on all nodes.
s/architecture on/CPU architecture in/

2024-01-11 13:36 UTC, willfurnass commented on FAQs.rst
> + - Recompile your program without optimisations for processor architecture.
>  - Recompile your program without optimisations for processor architecture. 

Again, I suggest omitting

2024-01-11 13:36 UTC, willfurnass commented on FAQs.rst
> + - Recompile on the node type (CPU or GPU) you intend to run your job.
Or cross-compile for that other CPU or GPU type.

2024-01-11 13:36 UTC, willfurnass commented on FAQs.rst
> + - Run your job on the type of architecture it was compiled for (CPU or GPU node).
> Run your job on the type of architecture it was compiled for (CPU or GPU node).

That's not really an _option_; users will always want to do this.

2024-01-11 13:36 UTC, willfurnass commented on FAQs.rst
> +Since Stanage has distinct GPU and CPU node architectures, you have several options:
GPUs: what error message(s) do users get when attempting to run a CUDA program compiled with support for a particular compute capability on a GPU that only provides older compute capabilities?

Perhaps we could handle the GPU case in this section by just saying that there are similar concerns/issues with GPU programs then x-reference to info elsewhere in these docs re compute capabiltiies.

2024-01-11 13:36 UTC, willfurnass commented on FAQs.rst
> +If your program fails with an **Illegal Instruction** error then it may have been compiled using (and optimised for) one type of processor but is running on another.
Could also x-ref to https://docs.hpc.shef.ac.uk/en/latest/referenceinfo/computer-architecture/quick-start.html#instruction-sets near the start of this section?

2024-01-11 13:36 UTC, willfurnass commented on FAQs.rst
> +'Illegal Instruction' errors
Overall, feels like this section could be quite a bit more concise.

2024-01-11 14:47 UTC, Carldkennedy commented on FAQs.rst
> +'Illegal Instruction' errors
Thanks Will. Concise is better. Left the mention of GPUs out for now.

2024-01-11 16:17 UTC, willfurnass reviewed
Suggestion for wording - feel free to ignore/challenge!

2024-01-11 16:17 UTC, willfurnass commented on FAQs.rst
> +If your program fails with an **Illegal Instruction** error then it may have been compiled using (and optimised for) one type of processor but is running on another (see :ref:`Instruction sets <instr
Tried re-writing this section:

```
If attempts to run a binary executable program fail with an ``Illegal Instruction`` error then 
your executable program (or a dynamically-linked library) may have been compiled so as to 
make more optimal use of the :ref:`Instruction set <instruction_sets>` of a particular CPU architecture (an *optimised binary*), 
but you're running the executable on CPU(s) that use a slightly different instruction set.

For example, you may have a executable program optimised for the Intel Icelake CPU instruction set but
you find it fails to run on AMD Milan CPUs, or
you might be trying to run a binary optimised for a very new Intel CPU architecture on an older model of Intel CPU.

For this reason we recommend that you avoid copying binary executables on to the HPC systems
and instead (re)compile programs and libraries on the HPC systems instead where possible.

This has the added benefits of ensuring that:

* Programs/libraries are compiled against the versions of dependencies provided on the HPC systems.
* Program/libraries are more likely to make use of the more advanced features of the CPU models in the HPC systems, 
  which could result in better performance/efficiency.
```

Thoughts?

2024-01-11 16:17 UTC, willfurnass commented on FAQs.rst
> +If your program fails with an **Illegal Instruction** error then it may have been compiled using (and optimised for) one type of processor but is running on another (see :ref:`Instruction sets <instr
Also, sorry but not sorry for the semantic line endings :)

2024-01-11 16:21 UTC, Carldkennedy commented on FAQs.rst
> +If your program fails with an **Illegal Instruction** error then it may have been compiled using (and optimised for) one type of processor but is running on another (see :ref:`Instruction sets <instr
Very clear, much better. Thanks @willfurnass

2024-01-11 16:30 UTC, Carldkennedy commented on FAQs.rst
> +If your program fails with an **Illegal Instruction** error then it may have been compiled using (and optimised for) one type of processor but is running on another (see :ref:`Instruction sets <instr
Added a callout box to draw attention to recommendation

2024-01-11 16:55 UTC, willfurnass approved these changes

2024-01-11 16:57 UTC, merged