First draft for port forwarding and ssh keys
rcgsheffield/sheffield_hpc pull request #2000
Opened 2024-02-29 14:32 UTC by nikishe

2024-03-01 12:25 UTC, Carldkennedy requested changes
LGTM. Suggested some grammatical changes and a few callouts to be added

2024-03-01 12:25 UTC, Carldkennedy commented on hpc/sshkeys.rst
> +        For users on windows using mobaxterm you can simply add your private key to any of the profiles you have setted up as shown in the image below. This will open a file explorer window that will
```suggestion
        For users on windows using mobaxterm you can simply add your private key to any of the profiles you have set up as shown in the image below. This will open a file explorer window that will allow you to select your private key.
```

2024-03-01 12:25 UTC, Carldkennedy commented on stanage/software/apps/jupyter.rst
> +The HPC clusters are only able to host a jupyter notebook work space in an interactve session. To install and run Jupyter please follow these steps.
```suggestion
The HPC clusters are only able to host a jupyter notebook work space in an interactive session. To install and run Jupyter please follow these steps.
```

2024-03-01 12:25 UTC, Carldkennedy commented on stanage/software/apps/jupyter.rst
> +5. If it's your first time using Jupyter, you will need to create a notebook configuration file. The following command will create ``jupyter_notebook_config.py`` in your home folder ``~/.jupyter/jupy
```suggestion
5. If it's your first time using Jupyter, you will need to create a notebook configuration file. The following command will create ``jupyter_notebook_config.py`` in your home directory ``~/.jupyter/jupyter_notebook_config.py``.
```

2024-03-01 12:25 UTC, Carldkennedy commented on stanage/software/apps/jupyter.rst
> +3. Activate an anaconda environment ( This can be an existing one or the one you created in step 2. )
```suggestion
3. Activate an Anaconda environment (This can be an existing one or the one you created in step 2).
```

2024-03-01 12:25 UTC, Carldkennedy commented on stanage/software/apps/jupyter.rst
> +2. Create  an :ref:`anconda <python_stanage>` environment. (If you already have an existing environment, jump to step 3)
```suggestion
2. Create  an :ref:`anaconda <python_stanage>` environment. (If you already have an existing environment skip to step 3)
```

2024-03-01 12:25 UTC, Carldkennedy commented on stanage/software/apps/jupyter.rst
> +4. Install Jupyter using ``pip``.
```suggestion
4. Install Jupyter using ``pip`` :
```

2024-03-01 12:25 UTC, Carldkennedy commented on stanage/software/apps/jupyter.rst
> +6. Set up a password for your Jupyter notebook (This is only done once). To do this, use the command:
```suggestion
6. Set up a password for your Jupyter notebook (this only needs doing once), with the following command:
```

2024-03-01 12:25 UTC, Carldkennedy commented on stanage/software/apps/jupyter.rst
> +7. Now you are ready to start jupyter
```suggestion
7. Now you are ready to start Jupyter:
```

2024-03-01 12:25 UTC, Carldkennedy commented on stanage/software/apps/jupyter.rst
> +The above command will produce output similar to the following example:
```suggestion
This will produce output similar to the following:
```

2024-03-01 12:25 UTC, Carldkennedy commented on stanage/software/apps/jupyter.rst
> +Accessing Jupyter On A Web Browser
```suggestion
Accessing Jupyter with a Web Browser
```

2024-03-01 12:25 UTC, Carldkennedy commented on stanage/software/apps/jupyter.rst
> +Once you have completed the above steps, you are ready to access jupyter on a web browser. There are two ways to do this:
```suggestion
Once you have completed the above steps, you are ready to access Jupyter with a web browser. There are two ways to do this:
```

2024-03-01 12:25 UTC, Carldkennedy commented on stanage/software/apps/jupyter.rst
> +.. image:: /images/flight_desktop_session.png
Suggest smaller image, maybe just the icon selection

2024-03-01 12:25 UTC, Carldkennedy commented on stanage/software/apps/jupyter.rst
> +Please note the above command is heavily dependant on the node you launched  jupyter notebook.
Suggest adding a note callout:
Replace<IP Address> with.....

2024-03-01 12:25 UTC, Carldkennedy commented on stanage/software/apps/jupyter.rst
> +For example step 7  of the ``Installing and Running Jupyter Notebooks`` section was launched in worker nodeoo2, the command would be :
```suggestion
For example, if we launched Jupyter on interactive node002 then the command would be :
```

2024-03-01 12:25 UTC, Carldkennedy commented on stanage/software/apps/jupyter.rst
> +3. Once step 2 has run and succesful, you just need to open a browser (Chrome/Edge/Mozilla etc) on your machine and enter the address containing  ``localhost`` from step 7  of the ``Installing and Ru
```suggestion
3. Open a browser (Chrome/Edge/Mozilla etc) on your machine and enter the address we noted earlier containing  ``localhost``  
```

2024-03-01 12:25 UTC, Carldkennedy commented on stanage/software/apps/jupyter.rst
> +
need to add note callout to take not of the http://127.0.0.1:8889/tree address

2024-03-01 12:39 UTC, nikishe commented on stanage/software/apps/jupyter.rst
> +Please note the above command is heavily dependant on the node you launched  jupyter notebook.
added a note

2024-03-01 12:45 UTC, nikishe commented on stanage/software/apps/jupyter.rst
> +
added a note

2024-03-01 12:46 UTC, nikishe commented on stanage/software/apps/jupyter.rst
> +For example step 7  of the ``Installing and Running Jupyter Notebooks`` section was launched in worker nodeoo2, the command would be :
updated this in a note

2024-03-01 12:54 UTC, nikishe commented on stanage/software/apps/jupyter.rst
> +.. image:: /images/flight_desktop_session.png
smaller image added

2024-03-01 15:48 UTC, jkwmoore commented
@nikishe When making corrections / changes please don't use a commit for each individual change you make.

If possible, try to make these sensibly grouped under a single commit per type of thing you are changing. This will help reviewers if they are reviewing large amounts of changes as they can work forward in the PR by each commit.

e.g. 1 commit for all of Carl's corrections, or 1 commit which covers all spelling, grammar corrections etc...

Each time you make a commit, (depending on people's notification settings of which I am at least partially to blame for in my case) people you've elected to review will get emailed for each. e.g. I see 12 GitHub emails in the last 5 mins for this PR.

2024-03-04 14:11 UTC, f-allian requested changes
@nikishe Thanks for this Niki, I've added some comments below

2024-03-04 14:45 UTC, f-allian requested changes
@nikishe It would be worth mentioning before this step to `module load Anaconda3` to avoid any confusion of thinking they need to install anaconda/miniconda.

2024-03-04 14:45 UTC, f-allian commented on stanage/software/apps/jupyter.rst
> +
@nikishe It would be worth mentioning before this step to `module load Anaconda3` to avoid any confusion of thinking they need to install anaconda/miniconda.

2024-03-04 14:45 UTC, f-allian commented on stanage/software/apps/jupyter.rst
> +
@nikishe I can only successfully execute this (Windows 11 OS) in Powershell/cmd prompt, and not in my bash terminal.

2024-03-04 14:45 UTC, f-allian commented on stanage/software/apps/jupyter.rst
> +    The above command is heavily dependant on the node you launched  Jupyter notebook. S
@nikishe Typo "S" after "Jupyter notebook."

2024-03-04 15:51 UTC, nikishe commented on stanage/software/apps/jupyter.rst
> +    The above command is heavily dependant on the node you launched  Jupyter notebook. S
corrected

2024-03-04 15:57 UTC, nikishe commented on stanage/software/apps/jupyter.rst
> +
I have altered the sentence to show the module load and environment creation. I did not add the code though as the hyper link deals with all these

2024-03-04 16:20 UTC, merged

2024-03-04 16:32 UTC, jkwmoore commented
This doesn't appear to have gone via review? Unless I'm told otherwise in the next 30 seconds I am reverting it.

2024-03-04 16:40 UTC, nikishe commented
> mmit that referenced this pull request

Carl and Farhad reviewed it