First draft for port forwarding and ssh keys
rcgsheffield/sheffield_hpc pull request #2011
Opened 2024-03-06 09:44 UTC by jkwmoore

Continuing from https://github.com/rcgsheffield/sheffield_hpc/pull/2000

@Carldkennedy @f-allian  probably worth re-adding any requested changes here.

2024-03-06 11:52 UTC, fredsonnenwald commented on hpc/sshkeys.rst
> +        Check that you have ssh agent installed and running with the following command.
What's the difference between SSH Agent, SSH-AGENT, and ssh agent?

2024-03-06 11:52 UTC, fredsonnenwald commented on stanage/software/apps/jupyter.rst
> +The HPC clusters are only able to host a Jupyter notebook work space in an interactive session. To install and run Jupyter please follow these steps.
Will mentioned the possibility of just rendering a notebook?

2024-03-06 11:54 UTC, fredsonnenwald commented on stanage/software/apps/jupyter.rst
> +#. Using flight-desktop (Recommended)
I think there might be some assumptions here about your flight session being on the same node as your Jupyter session.

2024-03-06 11:55 UTC, fredsonnenwald commented on stanage/software/apps/jupyter.rst
> +6. Set up a password for your Jupyter notebook (this only needs doing once), with the following command:
Really need to emphasise the need for there to be a password

2024-03-06 14:06 UTC, jkwmoore commented on hpc/sshkeys.rst
> +3. Add SSH private Key to mobaXterm or SSH-Agent on your local machine. This will vary based on your operating system and whether you are using a GUI ssh client like mobaxterm or ssh on a terminal.
Personally I want to see a general move away from X11 forwarding and MobaXterm/Putty. The latter still leverage a separate exclusive SSH ecosystem which isolates users from the arguably much better OpenSSH stack and dependent software.

OpenSSH also natively supports the tooling for Smallstep (which enables increased security via MFA enabled ephemeral SSH key provisioning). Smallstep is likely to be an enforced posture for security / risk reasons when this becomes possible.

I would prefer to see us move to a posture where we divest from the Putty / Moba ecosystem in favor of native terminal tooling for each OS and/or leveraging OpenSSH which should be receiving regular vendor updates from the OS maintainer (other clients are getting less regular TLC in general I think.)


This gives the flexibility to use every client which supports the usage of SSH agents on any platform for both SSH and data transfer. Assuming we converge on a specific file transfer method (Filezilla?) this should also reduce support / training needs.

n.b. WSL SSH shouldn't be needed (but could be used) since Windows now has native OpenSSH support. I have requested that the managed desktop ensure this is also available everywhere.

2024-03-06 14:08 UTC, jkwmoore commented on stanage/software/apps/jupyter.rst
> +#. Using flight-desktop (Recommended)
I'm expecting the user should be making the request for the interactive flight-desktop session then spawning the notebook within it here.

2024-03-06 14:59 UTC, f-allian requested changes

2024-03-06 14:59 UTC, f-allian commented on hpc/sshkeys.rst
> +2. Once the keys have been succesfully created, we need to copy the public key to the HPC. Your public key is the file with the extension ``.pub``
@jkwmoore I think we should be more explicit here about the importance of the difference between these keys. Something like: "This will generate 2 different keys, 1 private one, and 1 public one. You ***must not!*** share your private key with anyone." etc.

2024-03-06 14:59 UTC, f-allian commented on stanage/software/apps/jupyter.rst
> +
@jkwmoore With the conversations we had in Slack earlier this week, how much do we want to encourage using Jupyter notebooks for HPC purposes? Should we caveat this by saying something like "if you absolutely must use Jupyter Notebooks, then..."

2024-03-06 14:59 UTC, f-allian commented on stanage/software/apps/jupyter.rst
> +
@jkwmoore Might be worth highlighting this only works in Windows (i.e. powershell/cmd prompt) and not any other OS (from mine and Niki's testing).

2024-03-06 15:31 UTC, fredsonnenwald commented on hpc/sshkeys.rst
> +3. Add SSH private Key to mobaXterm or SSH-Agent on your local machine. This will vary based on your operating system and whether you are using a GUI ssh client like mobaxterm or ssh on a terminal.
I really like the idea of using ssh built into Windows, particularly as for teaching it's an identical experience independent of OS. (And it's much easier than WSL!) 

I'm not sure built-in is necessarily better on a regular updates front. The file modification date for ssh on my Laptop is early 2022 with version OpenSSH_8.1p1. For context Ubuntu LTS desktop has 8.9p1, and 9.6p1 is the current release.

2024-03-07 10:57 UTC, nikishe commented on hpc/sshkeys.rst
> ++------------------------------------------------------+------------------------------------------------------+----------------------------------------------------------------------------------------
There are 2 interactive nodes, node 1 and node 2 . This table showed their IP address

2024-03-07 11:09 UTC, nikishe commented on hpc/sshkeys.rst
> +3. Add SSH private Key to mobaXterm or SSH-Agent on your local machine. This will vary based on your operating system and whether you are using a GUI ssh client like mobaxterm or ssh on a terminal.
@fredsonnenwald ssh is perfect and im currently planting the seed for tabby (supports all OSs) , but atm docs mostly  concentrate on mobaxterm as the recommended option but this is platform dependant and abit of a pain to support and teach as you have to give 3 different paths based on user OS .

2024-03-07 11:11 UTC, nikishe commented on hpc/sshkeys.rst
> +        Check that you have ssh agent installed and running with the following command.
thats me being inconsistent

2024-03-07 11:11 UTC, nikishe commented on stanage/software/apps/jupyter.rst
> +
I have gone back to the 4 users and we are having a stance on flight

2024-03-07 11:16 UTC, nikishe commented
After our discussion , I am closing this pull request. Might revive it once we get managed ssh keys

2024-03-07 11:16 UTC, closed without merging