Out of Memory FAQ
rcgsheffield/sheffield_hpc pull request #2061
Opened 2024-04-02 10:20 UTC by beckywilks

Hi, 

I added an FAQ for Out of Memory error messages. See #2038 

This is my first attempt at documentation so all advice is welcome. 

Becky :)

2024-04-02 10:57 UTC, jkwmoore commented
As a side note, we can link PRs to issues with the development side tab on the PR page in Github:

![image](https://github.com/rcgsheffield/sheffield_hpc/assets/69149348/5f59c3a1-fc81-47fb-aefc-ce91ec180ba6)

2024-04-04 08:57 UTC, jkwmoore commented
Apologies, I forgot to make my review fully live before you cracked on with amending. Making these visible now.

2024-04-04 08:57 UTC, jkwmoore requested changes

2024-04-05 07:55 UTC, nikishe reviewed
Congratulation on your first pull request. I have added a small suggestion to make one of your sentences short and snappy

2024-04-05 07:55 UTC, nikishe commented on FAQs.rst
> +For both interactive and batch jobs, resources are requested for the job. When 'Out of Memory' and 'OOM' errors occur it means not enough memory has been allocated for the job to run to completion.
```suggestion
When "Out of Memory" (OOM) errors occur in an interactive or batch  session , it indicates insufficient memory has been allocated for the job to run to completion.
```

2024-04-10 10:38 UTC, nikishe approved these changes
LGTM

2024-04-15 09:39 UTC, Carldkennedy approved these changes
LGTM

2024-04-15 09:39 UTC, Carldkennedy commented on FAQs.rst
> +When "Out of Memory" (OOM) errors occur in an interactive or batch  session , it indicates insufficient memory has been allocated for the job to run to completion.
```suggestion
When "Out of Memory" (OOM) errors occur in an interactive or batch session, it indicates insufficient memory has been allocated for the job to run to completion.
```

2024-04-25 11:41 UTC, jkwmoore requested changes
Please merge when the separator is in place. Ta!

2024-04-25 11:41 UTC, jkwmoore commented on FAQs.rst
>  |br|
```suggestion
-----
```

Looks like we don't really need the additional break line but we are missing a separator.

2024-04-25 15:31 UTC, jkwmoore approved these changes

2024-04-26 14:51 UTC, nikishe approved these changes

2024-05-15 11:36 UTC, closed without merging