Add FAQ on ACL change of ownership
rcgsheffield/sheffield_hpc pull request #2062
Opened 2024-04-02 14:16 UTC by nahceigna

Hi all,

I have included an FAQ entry showing users how to change the ACL ownership of files/folders.

2024-04-02 14:44 UTC, Carldkennedy requested changes
Well done on your first commit. Added a few comments and suggested a few changes.

2024-04-02 14:44 UTC, Carldkennedy commented on FAQs.rst
> +Normal users will not have the permission to **chown** since they are not being root or in sudoers. Therefore, the only valid method for transferring ownership of files/folders is to make
We try to be succinct where possible. Maybe something like:
Cluster users can not use **chown** for transferring ownership of files/folders, however it is possible using Access Contol Lists (ACLs).   
The continue with: The following assumes...

2024-04-02 14:44 UTC, Carldkennedy commented on FAQs.rst
> +The following assumes user1 is the current owner and user2 is going to be the new owner. Please change the ownership of the files/folders using the following instructions:
```suggestion
The following assumes user1 is the current owner and user2 is going to be the new owner:
```

2024-04-02 14:44 UTC, Carldkennedy commented on FAQs.rst
> +1. user1 makes the files/folders to be changed ownership available to read by user2, most likely with Linux ACLs:
```suggestion
1. user1 makes the files/folders available to read by user2 with Linux ACLs:
```

2024-04-02 14:44 UTC, Carldkennedy commented on FAQs.rst
> +
give an example output

2024-04-02 14:44 UTC, Carldkennedy commented on FAQs.rst
> +5. user2 moves the folder back where it was before:
```suggestion
5. user2 moves the folder back to it's original location:
```

2024-04-03 16:16 UTC, jkwmoore requested changes
Where we have the usernames 'user1' and 'user2' in line, we might want to highlight these using bold formatting (`**bold**`) or via inline code highlighting (` ``inline code`` `).

If we're using FACLs we should probably also link out to some more detail and potentially provide a warning that FACLs can be hard to detect but can be seen via the extra ``+`` you can see via the ls command where they are present.

e.g.

```
my_user@work-ubuntu-vm:/tmp/tmp.x08Uc3hZJ1$ ls -al
total 28
drwx------   2 my_user my_user  4096 Apr  3 16:47 .
drwxrwxrwt  27 root   root   20480 Apr  3 17:12 ..
-rw-rwxr--+  1 root   root       0 Apr  3 16:47 testfile
my_user@work-ubuntu-vm:/tmp/tmp.x08Uc3hZJ1$ getfacl testfile 
# file: testfile
# owner: root
# group: root
user::rw-
user:my_user:rwx
group::r--
mask::rwx
other::r-
```

If we wanted to be gucci, we could also use this as an opportunity to try out ASCII cinema to provide a "running example".

https://asciinema.org/

https://pypi.org/project/sphinxcontrib.asciinema/

2024-04-03 16:16 UTC, jkwmoore commented on FAQs.rst
> +Cluster users cannot use **chown** for transferring ownership of files/folders. However, it is possible using Access Control Lists (ACLs).
For this part I think we will want to explain a little more background or users may have further unanswered questions. I was thinking about:

- The 'chown' command can only be successfully executed by the root user on any linux system(why? security - https://unix.stackexchange.com/questions/27350/why-cant-a-normal-user-chown-a-file/27374#27374)

- HPC users are not allowed to use the root account or assume its permissions (why? security on a shared system like HPC)

- Explain in human terms what we're doing before we give CLI type instructions e.g. we will bypass these limitations by giving the 2nd user read permissions on the data so they can make a copy of their own, then we can delete the original data.

2024-04-04 16:45 UTC, Carldkennedy reviewed
Added a few comments and suggestions

2024-04-04 16:45 UTC, Carldkennedy commented on FAQs.rst
> +Cluster users are not allowed to use the root account for system administrators to control and ensure the security of all users.
```suggestion
Cluster users are not allowed to use the root account due to it's elevated privileges, it is reserved for system administrators to ensure the security of all users.
```

2024-04-04 16:45 UTC, Carldkennedy commented on FAQs.rst
> +Thus, they cannot use **chown** for transferring ownership of files/folders due to the possibility of leading to security vulnerabilities.
```suggestion
Thus, they cannot use **chown** for transferring ownership of files/folders.
```

2024-04-04 16:45 UTC, Carldkennedy commented on FAQs.rst
> +The files/folders have to be stored in public Fastdata areas, detailed instructions are contained in the :ref:`fastdata_dir`.
Could have this as item 1 on the list. I.e make sure user2 has access to the folder/files

2024-04-05 08:07 UTC, nikishe reviewed
Second pull request already. Good job. Few suggestion from the team , but this looks really good so far

2024-04-05 08:07 UTC, nikishe commented on FAQs.rst
> +Cluster users are not allowed to use the root account for system administrators to control and ensure the security of all users.
You are not wrong but I think "HPC users" would more clear for newbies. Ill let you make the call though.

2024-04-05 09:36 UTC, jkwmoore commented on FAQs.rst
> +Cluster users are not allowed to use the root account for system administrators to control and ensure the security of all users.
Here I think we probably want reword a bit to indicate 

> "Only system administrators are granted access to the root account (superuser privileges) for security reasons."

Can possibly link on `superuser privileges`  out to: https://en.wikipedia.org/wiki/Superuser

Side note on "it's" versus "its": the former contraction is equivalent to "it is", so should only be used where that works.

2024-04-05 09:42 UTC, beckywilks commented on FAQs.rst
> +        cp -R /mnt/parscratch/users/user1/public/the/directory/changing/ownership/ my/tmp/directory
If someone is following this through they probably won't have a tmp dir. Maybe add a line 'mkdir my/tmp/directory/'. I'd just make it part of step 2, no need for an extra step.

Most users will probably know to make a directory but I think it will make for a more streamlined process for users following it through. :)

2024-04-05 09:43 UTC, jkwmoore commented on FAQs.rst
> +Thus, they cannot use **chown** for transferring ownership of files/folders due to the possibility of leading to security vulnerabilities.
Think we're also missing some background on: "As using chown requires owning the file or being root for security reasons, thus it is not possible for a non-root user to reassign ownership."

Where "security reasons" can link out to https://unix.stackexchange.com/a/27374

2024-04-10 10:37 UTC, nikishe approved these changes
LGTM

2024-04-10 10:47 UTC, beckywilks approved these changes

2024-04-15 09:48 UTC, Carldkennedy approved these changes
LGTM

2024-04-24 16:29 UTC, jkwmoore commented on FAQs.rst
> +However, it is achievable using Access Control Lists (ACLs).
```suggestion
For security reasons only system administrators are granted access to the root account (`superuser privileges <https://en.wikipedia.org/wiki/Superuser>`_)
and as successfully using the **chown** command `requires root account permissions <https://unix.stackexchange.com/a/27374>`_ it is not possible for a non-root user to directly reassign ownership.
However it is possible to do so indirectly by using Access Control Lists (ACLs).
```

2024-04-24 16:30 UTC, jkwmoore commented on FAQs.rst
> +8. **user1** deletes the existing folder recursively:
We might want a warning admonishment here that they should check with user2 the files have transferred prior to deletion as the fastdata areas do not have backups.

2024-04-24 16:31 UTC, jkwmoore approved these changes
LGTM - just a suggestion to making the wording a bit less clunky and we may want to add a warning pop out.

2024-04-25 11:44 UTC, nikishe approved these changes

2024-04-25 12:07 UTC, jkwmoore approved these changes
Added a missing separator but otherwise good to merge.

2024-04-25 13:29 UTC, merged