April newsletter
rcgsheffield/sheffield_hpc pull request #2071
Opened 2024-04-11 11:35 UTC by nikishe

April news letter

2024-04-12 11:31 UTC, willfurnass requested changes
Sorry, made quite a few suggestions - hope you don't mind!

2024-04-12 11:31 UTC, willfurnass commented on newsletter/20240415.rst
> +FastData Storage
```suggestion
Lustre filesystems
```

2024-04-12 11:31 UTC, willfurnass commented on newsletter/20240415.rst
> +This month we `Fastdata <https://docs.hpc.shef.ac.uk/en/latest/hpc/filestore.html#fastdata-areas>`_ on the HPC clusters. Fast data uses a parallel, distributed file system known as lustre. Its distri
Hope you don't mind but I've suggested some slightly different wording for this section:

You are likely aware that the Stanage and Bessemer systems :ref:`each contain a large Lustre parallel filesystem<fastdata_dir>`.

* `/mnt/parscratch` on Stanage
* `/fastdata` on Bessemer

We would like to draw your attention to several characteristics of these Lustre filesystems

* They provide lots of temporary storage with no quotas;
* **They are not backed up;**
* They offer good performance when working with larger files than e.g. home directories - Lustre performance scales well with the number of filesystem clients, plus on Stanage connections to
 Lustre are via high-bandwidth (100 Gbps), low-latency network links;
* **They perform poorly when working with lots of small files (e.g. files only a few kB in size)** (see `this blog post <https://walkingrandomly.com/?p=6167>_`).  Even just enumerating or deleting millions of files from a Lustre filesystem can take days;
* **They perform poorly when you have a large number (>1000) of files or directories within a directory.**

Recommendations:

* Do not use these Lustre filesystems for long-term storage
* Prefer to work with larger files where possible.  For example can you combine output data within one large HDF5 file instead of creating lots of small text files?
* Try to limit the number of files or directories within a directory.
* If using interative workflows e.g. machine learning or fluid dynamics software then consider outputting data to Lustre less frequently than every time/simulation step e.g. every 1000 steps
.
* If you have concerns about how many files your workflow might create on Lustre then consider running some short tests before launching big jobs.

2024-04-12 11:31 UTC, willfurnass commented on newsletter/20240415.rst
> +** The platform team also added the command ``show-fastdata-consumption`` which shows the total usage storage by all our users on fast data. For most users this can be a proactive way of checking if
```suggestion
** To see how much you are currently storing on Lustre please run the new ``show-fastdata-consumption``command.  This can be a proactive way of checking if its time to do some housekeeping on some of your data hosted on Lustre. **
```

2024-04-12 11:31 UTC, willfurnass commented on newsletter/20240415.rst
> +- Migrate to our research storage solution (X-Drive), which offers up to 10TB of storage for research groups. This offers a secure, encrypted and backed up option to meet any Data storage and GDPR ne
* 10TB: for free per PI; can buy more than that
* encrypted: at rest, and also in transit if not accessed over NFS
* 'to meet any Data storage and GDPR needs' -> I think we should be careful about saying things like - I suggest you discuss with Ross.

2024-04-12 11:31 UTC, willfurnass commented on newsletter/20240415.rst
> +- Migrate to our research storage solution (X-Drive), which offers up to 10TB of storage for research groups. This offers a secure, encrypted and backed up option to meet any Data storage and GDPR ne
Simplest to trim down your 2nd bullet and rely on students.sheffield.ac.uk/it-services/research/storage to cover most points re benefits, caveats etc?

2024-04-12 11:31 UTC, willfurnass commented on newsletter/20240415.rst
> +For users using Pytorch and the GPUs to carry out experiments, using a newer Pytorch container (24.02 rather than 23.07) should fix a bug which made the H100 PCIE slower than the A100. You should see
```suggestion
For users using Pytorch with the GPUs in Stanage, using a newer Pytorch container (24.02 rather than 23.07) should fix a bug which made the H100 GPUs  slower than the A100 GPUs. You should see an almost 50% performance boost between the two Pytorch versions as discovered by the benchmarks Peter Heywood in the `RSE team<https://rse.shef.ac.uk/>`__ ran. Performance on the A100 stays the same.
```

2024-04-12 12:17 UTC, nikishe commented on newsletter/20240415.rst
> +Below are our research computing key training dates for March. You can register for these courses and more at  `Research Computing Training <https://sites.google.com/sheffield.ac.uk/research-training
Added the first 10 days of may.

2024-04-12 12:25 UTC, nikishe commented on newsletter/20240415.rst
> +Recently, many of you received emails regarding Google Drive's new `15GB data cap <https://staff.sheffield.ac.uk/it-services/storage/google-data-cap-project>`_, resulting from Google's 1PB limit on u
updated

2024-04-12 12:27 UTC, nikishe commented on newsletter/20240415.rst
> +For users using Pytorch and the GPUs to carry out experiments, using a newer Pytorch container (24.02 rather than 23.07) should fix a bug which made the H100 PCIE slower than the A100. You should see
updated

2024-04-12 13:02 UTC, nikishe commented on newsletter/20240415.rst
> +For users of licensed software such as MATLAB and Ansys, please be mindful of license availability when submitting multiple jobs that will take huge fraction of licences from the pool. Please notify
I am going to reword it but I have added the github issue 2074 , which will address this

2024-04-12 16:06 UTC, nikishe commented on newsletter/20240415.rst
> +For users of licensed software such as MATLAB and Ansys, please be mindful of license availability when submitting multiple jobs that will take huge fraction of licences from the pool. Please notify
I am removing it and redo this in the future when we have found away to make the license count more transparent or whatever we come up with to solve issue 2074

2024-04-15 12:37 UTC, willfurnass commented
Also, would be good to add brief note on Grace Hoppers in Bede: they're avaiable and we'll cover in more detail in next newsletter.

2024-04-15 12:57 UTC, willfurnass commented
Suggested wording: 

> Grace Hopper GPU nodes available in the Bede HPC system
> 
> Three Grace Hopper that were added to the :ref:`Bede <bede>` HPC system are no longer in pilot and are available for general user.   Each of these nodes (two worker nodes and an interactive/login node) contains a tightly-coupled pairing of an NVIDIA H100 GPU ('Hopper') and an ARM ('Grace') CPU and should be very well suited to GPU compute problems that require lots of data sharing between CPU and GPU.  We'll cover benefits and performance in a future newsletter.  

> Grace Hopper usage documentation will be added to the Bede documentation site soon, but for now please see the `Bede Grade Hopper Pilot docs <https://bede-documentation.readthedocs.io/en/latest/usage/index.html#grace-hopper-pilot>`__ for a guide to getting started with them.

2024-04-15 14:59 UTC, willfurnass requested changes
LGTM as it stands but we still want to add a brief note about the pending OS upgrades under a top-level heading.

2024-04-15 15:44 UTC, willfurnass commented on newsletter/20240415.rst
> +The operating system on Stanage and Bessemer will be upgraded before the end of July. This upgrade ensures the security, stability and performance of our HPC infrastructure. Certain software packages
```suggestion
The operating system on Stanage and Bessemer will be upgraded in the next few months. This upgrade ensures the security, stability and performance of our HPC infrastructure. Certain software packages and applications may not be compatible with the new OS (Rocky 9). We encourage you to start thinking about utilising newer versions of software and libraries. We will provide further updates regarding the OS upgrade shortly, including timelines. 
```

2024-04-15 15:46 UTC, willfurnass requested changes
Thanks @Carldkennedy; changes mostly look good; suggested some minor tweaks.

Think the only larger section that now needs work is the bit on research shared areas (https://github.com/rcgsheffield/sheffield_hpc/pull/2071#discussion_r1562420875)

2024-04-16 09:04 UTC, willfurnass approved these changes
@Carldkennedy Like the wording tweaks re Research Shared Areas.  Ta.

2024-04-16 10:40 UTC, merged