File transfer selection decision tree
rcgsheffield/sheffield_hpc pull request #2084
Opened 2024-04-23 09:31 UTC by nahceigna

Hi all,

I created a decision tree for selecting the most suitable file transfer method and included in the [Transferring files — Sheffield HPC Documentation](https://docs.hpc.shef.ac.uk/en/latest/hpc/transferring-files.html#gsc.tab=0). Hope this can improve the clarity of the tools available.

![hpc-file-transfer-selection-decicsion-tree](https://github.com/rcgsheffield/sheffield_hpc/assets/66580732/f81144f9-7b5f-4fdb-8aa5-1595c5dcef58)

Thanks,
Angie

2024-04-23 14:32 UTC, nikishe commented
Hey Angie , great work but try limiting each pull requests to one task/goal.
The ACLs should be a separate PR to the file transfer. This will make life easier down the line when you are dealing with really big PRs

2024-04-23 14:42 UTC, nikishe commented on images/hpc-file-transfer-selection-decicsion-tree.png
Great work on your first image

2024-04-23 15:10 UTC, nikishe requested changes

2024-04-24 12:55 UTC, closed without merging

2024-04-24 12:55 UTC, nahceigna commented
Updates are in #2090.