EL9 Abaqus docs
rcgsheffield/sheffield_hpc pull request #2172
Opened 2024-07-05 11:05 UTC by desmfryan

Abaqus docs update for EL9

One tested version Abaqus 2023 on Rocky9 (Abaqus 2021 to be removed from /opt/apps/tuos/common)

Tested with iccifort/2020.1.217 (for user subroutines) via abaqus verify -all

2024-07-11 13:24 UTC, nikishe requested changes
Only one version in the doc, but 2 are installed

ABAQUS/2021
        ABAQUS/2023

2024-07-11 13:24 UTC, nikishe commented on stanage/software/apps/abaqus.rst
> +    module load ABAQUS/2023
All is correct but on el9 we have both 
       ```
 ABAQUS/2021
        ABAQUS/2023
```

2024-07-15 08:38 UTC, desmfryan commented on stanage/software/apps/abaqus.rst
> +    module load ABAQUS/2023
@nikishe ABAQUS/2021 does not work correctly & will be deleted today

2024-07-15 08:53 UTC, nikishe approved these changes
2021  irrelevant

2024-07-15 09:42 UTC, merged